{
  pkgs,
  lib,
  neg,
  impurity ? null,
  ...
}: let
  n = neg impurity;
  # Source Paths (used for linkImpure - must be Nix paths, not strings)
  kittyConf = ../../../files/kitty;
  nuConfDir = ../../../files/nushell;
  tmuxConfDir = ../../../files/tmux;
  ompConfig = ../../../files/shell/zsh/neg.omp.json;

  # Kitty Scrollback Path (for session variable)
  nixKsbPath = "${pkgs.vimPlugins.kitty-scrollback-nvim}/python/kitty_scrollback_nvim.py";
in
  lib.mkMerge [
    {
      # Packages and Scripts
      environment.systemPackages = [
        # Terminals
        pkgs.kitty # GPU-accelerated terminal with ligatures and image support

        # Shells
        pkgs.nushell # Modern shell with structured data pipelines
        pkgs.tmux # Terminal multiplexer for session management
        pkgs.oh-my-posh # Cross-shell prompt theme engine

        # Tools needed for kitty-panel
        pkgs.gum # TUI styling toolkit for shell scripts
        pkgs.btop # Resource monitor (CPU, memory, disks, network)
        pkgs.cava # Console audio visualizer
        pkgs.peaclock # Customizable clock for terminal
        pkgs.curl # HTTP client for weather fetching
      ];

      # Session variables
      environment.sessionVariables = {
        # Hint to Kitty for KSB
        KITTY_KSB_NIX_PATH = nixKsbPath;
      };
    }

    (n.mkHomeFiles {
      # Kitty Config
      ".config/kitty".source = n.linkImpure kittyConf;

      # Tmux Config
      ".config/tmux".source = n.linkImpure tmuxConfDir;

      # Nushell Config
      ".config/nushell/aliases.nu".source = n.linkImpure (nuConfDir + /aliases.nu);
      ".config/nushell/git.nu".source = n.linkImpure (nuConfDir + /git.nu);
      ".config/nushell/broot.nu".source = n.linkImpure (nuConfDir + /broot.nu);
      ".config/nushell/git-completion.nu".source = n.linkImpure (nuConfDir + /git-completion.nu);
      # We construct config/env manually to inject dynamic content if needed,
      # or just source them.
      ".config/nushell/config.nu".source = n.linkImpure (nuConfDir + /config.nu);

      # For env.nu, we append the oh-my-posh init
      ".config/nushell/env.nu".text =
        builtins.readFile "${nuConfDir}/env.nu"
        + ''

          # -- Generated by NixOS --
          $env.PROMPT_COMMAND = {||
            ${pkgs.oh-my-posh}/bin/oh-my-posh print primary --shell nu --config=${n.linkImpure ompConfig}
          }
          $env.PROMPT_COMMAND_RIGHT = ""
        '';
    })
  ]
