{ ... }:
{
  imports = [
    ./appimage/default.nix
    ./appimage/pkgs.nix
    ./args.nix
    ./cli/archives/pkgs.nix
    ./cli/default.nix
    ./cli/dev.nix
    ./cli/file-ops.nix
    ./cli/media.nix
    ./cli/monitoring.nix
    ./cli/network.nix
    ./cli/system.nix
    ./cli/text.nix
    ./cli/tmux/default.nix
    ./cli/tools.nix
    ./cli/ugrep.nix
    ./core/neg.nix
    ./db/pkgs.nix
    ./dev/android/default.nix
    ./dev/antigravity.nix
    ./dev/benchmarks/default.nix
    ./dev/editor/default.nix
    ./dev/editor/neovim/pkgs.nix
    ./dev/editor/pkgs.nix
    ./dev/elf/pkgs.nix
    ./dev/gcc/autofdo.nix
    ./dev/gdb/default.nix
    ./dev/git/pkgs.nix
    ./dev/hack/core.nix
    ./dev/hack/default.nix
    ./dev/hack/forensics.nix
    ./dev/hack/pentest/backdoor.nix
    ./dev/hack/pentest/database.nix
    ./dev/hack/pentest/default.nix
    ./dev/hack/pentest/explotation.nix
    ./dev/hack/pentest/fuzzing.nix
    ./dev/hack/pentest/passwords.nix
    ./dev/hack/pentest/recon.nix
    ./dev/hack/pentest/reversing.nix
    ./dev/hack/pentest/rfid.nix
    ./dev/hack/pentest/sniffing.nix
    ./dev/hack/pentest/steganography.nix
    ./dev/hack/pentest/web.nix
    ./dev/hack/pentest/wireless.nix
    ./dev/hack/sdr.nix
    ./dev/hack/vulnerability_scanners.nix
    ./dev/openxr/default.nix
    ./dev/pkgs/default.nix
    ./dev/python/pkgs.nix
    ./dev/unreal/default.nix
    ./diff-closures.nix
    ./documentation/settings.nix
    ./emulators/pkgs.nix
    ./features/apps.nix
    ./features/cli.nix
    ./features/core.nix
    ./features/default.nix
    ./features/dev.nix
    ./features/games.nix
    ./features/gui.nix
    ./features/media.nix
    ./features/misc.nix
    ./features/services.nix
    ./features/web.nix
    ./finance/tws.nix
    ./flake-preflight.nix
    ./flatpak/default.nix
    ./flatpak/pkgs.nix
    ./fonts/default.nix
    ./fun/default.nix

    ./fun/launchers-packages.nix
    ./fun/misc-packages.nix
    ./games/controllers.nix
    ./games/default.nix
    ./games/tuning.nix
    ./hardware/amdgpu.nix
    ./hardware/audio/dsp/pkgs.nix
    ./hardware/audio/pipewire/default.nix
    ./hardware/audio/pulseaudio/default.nix
    ./hardware/config.nix
    ./hardware/cooling.nix
    ./hardware/cpu/pkgs.nix
    ./hardware/gpu-corectrl.nix
    ./hardware/io/pkgs.nix
    ./hardware/liquidctl.nix
    ./hardware/pkgs.nix
    ./hardware/qmk/default.nix
    ./hardware/qmk/pkgs.nix
    ./hardware/udev-rules/default.nix
    ./hardware/uinput.nix
    ./hardware/usb-automount.nix
    ./hardware/video/amd/default.nix
    ./hardware/video/nvidia/rtx5090.nix
    ./hardware/video/pkgs/default.nix
    ./hardware/webcam/pkgs.nix
    ./llm/codex-config.nix
    ./llm/default.nix
    ./llm/ollama.nix
    # ./llm/open-webui.nix
    ./llm/pkgs.nix
    ./media/ai-upscale-packages.nix
    ./media/audio/apps-packages.nix
    ./media/audio/core-packages.nix
    ./media/audio/creation-packages.nix
    ./media/audio/default.nix
    ./media/audio/mpd-packages.nix
    ./media/audio/spotifyd.nix
    ./media/deepfacelab-docker.nix
    ./media/default.nix
    ./media/multimedia-packages.nix
    ./media/vapoursynth-packages.nix
    ./monitoring/grafana/default.nix
    ./monitoring/logs/default.nix
    ./monitoring/loki/default.nix
    ./monitoring/netdata/default.nix
    ./monitoring/php-fpm-exporter/default.nix
    ./monitoring/pkgs/default.nix
    ./monitoring/promtail/default.nix
    ./monitoring/sysstat/default.nix
    ./monitoring/vnstat/default.nix
    ./nix/bpftrace.nix
    ./nix/clblast.nix
    ./nix/default.nix
    ./nix/hyprland.nix
    ./nix/mpv-openvr.nix
    ./nix/multimon-ng.nix

    ./nix/packages-overlay.nix
    ./nix/settings.nix
    ./nix/wb32-dfu-updater.nix
    ./profiles/services.nix
    ./roles/default.nix
    ./roles/homelab.nix
    ./roles/media.nix
    ./roles/monitoring.nix
    ./roles/server.nix
    ./roles/workstation.nix
    ./secrets/pass/default.nix
    ./secrets/pkgs.nix
    ./secrets/yubikey/default.nix
    ./security/default.nix
    ./security/firejail.nix
    ./servers/_archive/audiobookshelf/default.nix
    ./servers/_archive/cleanuparr/default.nix
    ./servers/_archive/deemix/default.nix
    ./servers/_archive/filebot/default.nix
    ./servers/_archive/gitea/default.nix
    ./servers/_archive/gns3/default.nix
    ./servers/_archive/huntarr/default.nix
    ./servers/_archive/komga/default.nix
    ./servers/_archive/mcp-bridge/default.nix
    ./servers/_archive/open-webui/default.nix
    ./servers/_archive/parakeet/default.nix
    ./servers/_archive/plex/default.nix
    ./servers/_archive/portainer/default.nix
    ./servers/_archive/prowlarr/default.nix
    ./servers/_archive/qbittorrent-vpn/default.nix
    ./servers/_archive/qdrant/default.nix
    ./servers/_archive/radarr/default.nix
    ./servers/_archive/requestrr/default.nix
    ./servers/_archive/sabnzbd/default.nix
    ./servers/_archive/seafile/default.nix
    ./servers/_archive/searxng-mcp/default.nix
    ./servers/_archive/searxng/default.nix
    ./servers/_archive/sonarr/default.nix
    ./servers/_archive/syncthing/default.nix
    ./servers/_archive/tts-webui/default.nix
    ./servers/_archive/vllm/default.nix
    ./servers/_archive/whisper/default.nix
    ./servers/_archive/wyoming-openai/default.nix
    ./servers/adguardhome/default.nix
    ./servers/avahi/default.nix
    ./servers/bitcoind/default.nix
    ./servers/duckdns/default.nix
    ./servers/geoclue/default.nix
    ./servers/jellyfin/default.nix
    ./servers/mpd/default.nix
    ./servers/netdata/default.nix
    ./servers/openssh/default.nix
    ./servers/samba/default.nix
    ./servers/unbound/default.nix
    ./shell/default.nix
    ./shell/pkgs.nix
    ./shell/zsh.nix
    ./system/boot.nix
    ./system/boot/autofdo.nix
    ./system/boot/pkgs.nix
    ./system/environment.nix
    ./system/filesystems.nix
    ./system/guix.nix
    ./system/irqbalance.nix
    ./system/kernel/default.nix
    ./system/kernel/params.nix
    ./system/kernel/patches-amd.nix
    ./system/kernel/sysctl-mem-extras.nix
    ./system/kernel/sysctl-net-extras.nix
    ./system/kernel/sysctl-writeback.nix
    ./system/kernel/sysctl.nix
    ./system/net/bridge.nix
    ./system/net/default.nix
    ./system/net/nscd.nix
    ./system/net/pkgs.nix
    ./system/net/proxy.nix
    ./system/net/ssh.nix
    ./system/net/vpn/default.nix
    ./system/net/vpn/pkgs.nix
    ./system/net/vpn/xray.nix
    ./system/net/wifi.nix
    ./system/oomd.nix
    ./system/pkgs.nix
    ./system/preserve-flake.nix
    ./system/profiles/aliases.nix
    ./system/profiles/debug.nix
    ./system/profiles/default.nix
    ./system/profiles/performance.nix
    ./system/profiles/security.nix
    ./system/profiles/vm.nix
    ./system/profiles/work.nix
    ./system/swapfile.nix
    ./system/systemd/default.nix
    ./system/systemd/post-boot.nix
    ./system/systemd/timesyncd/default.nix
    ./system/tailscale.nix
    ./system/users.nix
    ./system/virt.nix
    ./system/virt/_archive/macos-vm.nix
    ./system/virt/default.nix
    ./system/virt/nemu.nix
    ./system/virt/pkgs.nix
    ./system/winapps.nix
    ./system/zram.nix
    ./text/default.nix
    ./text/manipulate-packages.nix
    ./text/notes-packages.nix
    ./text/read-packages.nix
    ./tools/default.nix
    ./tools/hiddify.nix
    ./tools/pkgs.nix
    ./torrent/default.nix
    ./user/bash.nix
    ./user/dbus.nix
    ./user/fonts.nix
    ./user/games/default.nix
    ./user/games/launchers.nix
    ./user/games/performance.nix
    ./user/games/vr.nix
    ./user/gui-packages.nix
    ./user/locale-pkgs.nix
    ./user/locale.nix
    ./user/locate.nix
    ./user/mail.nix
    ./user/nix-maid/apps/editors.nix
    ./user/nix-maid/apps/emacs.nix
    ./user/nix-maid/apps/gui-apps.nix
    ./user/nix-maid/apps/mpv/config.nix
    ./user/nix-maid/apps/mpv/default.nix
    ./user/nix-maid/apps/mpv/input.nix
    ./user/nix-maid/apps/mpv/package.nix
    ./user/nix-maid/apps/mpv/profiles.nix
    ./user/nix-maid/apps/mpv/scripts.nix
    ./user/nix-maid/apps/mpv/shaders.nix
    ./user/nix-maid/apps/nyxt.nix
    ./user/nix-maid/apps/transmission.nix
    ./user/nix-maid/apps/vicinae.nix
    ./user/nix-maid/cli/asciinema.nix
    ./user/nix-maid/cli/broot.nix
    ./user/nix-maid/cli/default.nix
    ./user/nix-maid/cli/emulators.nix
    ./user/nix-maid/cli/envs.nix
    ./user/nix-maid/cli/git.nix
    ./user/nix-maid/cli/local-bin.nix
    ./user/nix-maid/cli/monitoring.nix
    ./user/nix-maid/cli/search.nix
    ./user/nix-maid/cli/shells.nix
    ./user/nix-maid/cli/television.nix
    ./user/nix-maid/cli/tewi.nix
    ./user/nix-maid/cli/tig.nix
    ./user/nix-maid/cli/utils.nix
    ./user/nix-maid/cli/yazi.nix
    ./user/nix-maid/default.nix
    ./user/nix-maid/fun/fun-launchers.nix
    ./user/nix-maid/fun/nethack.nix
    ./user/nix-maid/fun/oss-games.nix
    ./user/nix-maid/fun/steam.nix
    ./user/nix-maid/gui/dunst.nix
    ./user/nix-maid/gui/qt.nix
    ./user/nix-maid/gui/quickshell.nix
    ./user/nix-maid/gui/theme.nix
    ./user/nix-maid/gui/walker.nix
    ./user/nix-maid/gui/xdg.nix
    ./user/nix-maid/hyprland/main.nix
    ./user/nix-maid/sys/autoclick.nix
    ./user/nix-maid/sys/dev.nix
    ./user/nix-maid/sys/distros.nix
    ./user/nix-maid/sys/enchant.nix
    ./user/nix-maid/sys/flatpak.nix
    ./user/nix-maid/sys/gpg.nix
    ./user/nix-maid/sys/khal.nix
    ./user/nix-maid/sys/mail.nix
    ./user/nix-maid/sys/media.nix
    ./user/nix-maid/sys/misc.nix
    ./user/nix-maid/sys/nekoray.nix
    ./user/nix-maid/sys/pipewire.nix
    ./user/nix-maid/sys/secrets.nix
    ./user/nix-maid/sys/services-manual.nix
    ./user/nix-maid/sys/text.nix
    ./user/nix-maid/sys/user-services.nix
    ./user/nix-maid/sys/vdirsyncer.nix
    ./user/nix-maid/web/aria.nix
    ./user/nix-maid/web/brave.nix
    ./user/nix-maid/web/browsing.nix
    ./user/nix-maid/web/chrome.nix
    ./user/nix-maid/web/defaults.nix
    ./user/nix-maid/web/edge.nix
    ./user/nix-maid/web/firefox.nix
    ./user/nix-maid/web/floorp.nix
    ./user/nix-maid/web/librewolf.nix
    ./user/nix-maid/web/misc.nix
    ./user/nix-maid/web/surfingkeys-server.nix
    ./user/nix-maid/web/tridactyl.nix
    ./user/nix-maid/web/vivaldi.nix

    ./user/nix-maid/web/yt-dlp.nix
    ./user/nvf.nix
    ./user/psd/default.nix
    ./user/session/chat.nix
    ./user/session/clipboard.nix
    ./user/session/default.nix
    ./user/session/greetd.nix
    ./user/session/hypr-bindings.nix
    ./user/session/hyprland.nix
    ./user/session/media.nix
    ./user/session/qt.nix
    ./user/session/quickshell.nix
    ./user/session/screenshot.nix
    ./user/session/terminal.nix
    ./user/session/theme.nix
    ./user/session/utils.nix
    ./user/theme-packages.nix
    ./user/wrappers/default.nix
    ./user/wrappers/tewi.nix
    ./user/xdg.nix
    ./web/browsers.nix
    ./web/default.nix
    ./web/nyxt.nix
  ];
}
