legacy_layout=0
position=top-left
font_size=20
background_alpha=0.35
toggle_hud=Shift_R+F12
toggle_logging=Shift_L+F2
toggle_fps_limit=Shift_L+F1

fps=1
frametime=1
frame_timing=1
gpu_stats=1
cpu_stats=1
gpu_temp=1
cpu_temp=1
vram=1
ram=1
io_read=1
io_write=1
gamemode=1
