{
  lib,
  mkBool,
  ...
}:
with lib;
{
  options.features = {
    hardware = {
      bluetooth.enable = mkBool "enable Bluetooth support" false;

      usbAutomount.enable = lib.mkEnableOption ''
        Enable udev-driven USB storage auto-mount via systemd service (mounts under /mnt/<label>).
      '';
    };
    input = {
      kanata.enable = mkBool "enable Kanata keyboard remapper (requires uinput module)" false;

      ruHotkeys = {
        enable = mkBool "enable per-window keyboard layout switching (us in hotkey-heavy apps)" false;

        usClasses = mkOption {
          type = types.listOf types.str;
          # Terminal windows are launched with custom kitty classes (M4+* scratch
          # binds in files/gui/hypr/hyprland.lua) — keep this list in sync.
          default = [
            "term" # plain shell (kitty --class term)
            "nwim" # nvim wrapper (kitty --class nwim)
            "music" # rmpc (M4+f)
            "teardown" # btop (M4+d)
            "torrment" # rustmission (M4+t)
            "vpn" # tun status (M4+u)
            "mixer" # ncpamixer (M4+C+p)
            "rebuild" # nh os switch (M4+S+n)
            "mpv" # video player: no text input, vim-style keys
          ];
          description = ''
            Hyprland window classes pinned to the us layout on focus. The list is
            exported to the layout daemon as `default_layouts` in
            ~/.config/hyprland-per-window-layout/options.toml (generated by
            hyprland/files.nix). Any other window starts on `usLayoutIndex` too
            (that is us under kb_layout = "us,ru") and then keeps whatever layout
            it was switched to — the daemon remembers the choice per window.
          '';
        };

        usLayoutIndex = mkOption {
          type = types.int;
          default = 0;
          description = "XKB group index of the us layout (kb_layout = us,ru invariant).";
        };

      };
    };
  };
}
