# Class patterns (shared)

# Workspace routing classes
$antigravity = ^(antigravity)$
$daw = ^(REAPER|Renoise)$
$dev = ^(nwim)$
$doc = ^(org.pwmt.zathura)$
$dw = ^(org.nicotine_plus.Nicotine)$
$games = ^(steam|Steam)$
$im = ^(im.riot.Riot)$
$keyboard = ^(Bazecor|wootility-lekker|Vial|via)$
$notes = ^(Obsidian)$
$obs = ^(obs)$
$patchbay = ^(qpwgraph|Carla2)$
$pic = ^swayimg$
$remote = ^(Vmware-view|xfreerdp|remmina|org.remmina.Remmina)$
$term = ^(term)$
$vid = ^(mpv)$
$vm = ^(.virt-manager-wrapped|qemu-system-x86_64|Qemu-system-x86_64)$
$web = ^(firefox|org\.mozilla\.firefox|librewolf|io\.gitlab\.librewolf-community|floorp|one\.ablaze\.floorp|floorpdeveloperedition|zen-beta|zen|chromium|org\.chromium\.Chromium|thorium-browser|com\.thorium\.Thorium|palemoon|net\.palemoon\.PaleMoon)$
$wine = ^(com.usebottles.bottles)$

# WinBoat workspace routing
$winboat = ^(winboat|WinBoat)$

# Scratchpad classes
$im_scratchpad = ^(KotatogramDesktop|Skype|Slack|TelegramDesktop|org.telegram.desktop|zoom)$
$music_scratchpad = ^(ncmpcpp|rmpc|music)$
$mail_scratchpad = ^(mutterfox|neomutt)$
$mixer_scratchpad = ^(ncpamixer|com.saivert.pwvucontrol)$
$torrment_scratchpad = ^(torrment)$
$teardown_scratchpad = ^(teardown)$
