-- Greeter Hyprland configuration (Lua, Hyprland 0.56).
-- Mirrors the desktop session display setup (10-bit + color management) so
-- the greeter output matches the main session (no washed-out colors).
hl.config({ autogenerated = false })

hl.monitor({ output = "DP-2", mode = "3840x2160@240", position = "0x0", scale = 2, vrr = 1, bitdepth = 10, cm = "auto" })
hl.monitor({ output = "DP-1", disabled = true })

hl.env("HOME", "/home/greeter")
hl.env("XDG_CACHE_HOME", "/home/greeter/.cache")
hl.env("XDG_CONFIG_HOME", "/home/greeter/.config")
hl.env("XDG_DATA_HOME", "/home/greeter/.local/share")

hl.config({
  input = { kb_layout = "us,ru", sensitivity = 0, follow_mouse = 1, accel_profile = "flat" },
  decoration = { blur = { enabled = false } },
  animations = { enabled = false },
  misc = {
    disable_hyprland_logo = true,
    disable_splash_rendering = true,
    disable_watchdog_warning = true,
    background_color = "rgba(00000000)",
    key_press_enables_dpms = true,
    mouse_move_enables_dpms = true,
  },
})

hl.on("hyprland.start", function()
  hl.exec_cmd("HOME=/home/greeter QML2_IMPORT_PATH=/etc/greetd/quickshell @quickshell@ -p /etc/greetd/quickshell/greeter/greeter.qml > /tmp/qs-greeter.log 2>&1 && pkill Hyprland")
end)
