-- =====================================================================
-- Hyprland configuration (Lua / hyprlang Lua API)
--
-- Migrated from the CachyOS `hyprland.lua` template and merged with the
-- NixOS config that used to be a set of hyprlang files (init.conf, vars.conf,
-- classes.conf, rules.conf, workspaces.conf, bindings/). Those files are gone:
-- this Lua file is the single source of truth, and the workspace list lives in
-- the `workspaces` table further down. Animations are defined inline below; the
-- separate animations/ preset directory no longer exists.
--
-- The CachyOS template provided the Lua API structure (hl.*); the behaviour is
-- the NixOS config's.
-- =====================================================================

hl.config({ autogenerated = false })

-- ---------------------------------------------------------------------
-- ---------------------------------------------------------------------
-- Plugins — none loaded.
-- Hyprland's Lua config mode auto-detects hyprland.lua and does NOT parse
-- the legacy hyprland.conf, so its `plugin = ...` lines are ignored. hy3 and
-- hyprspace were removed for the nixos-unstable (Hyprland 0.56) migration:
-- hyprspace's 0.55 CCompositor/monitor API no longer compiles against 0.56
-- and would need a substantial re-port. hy3 (0.55.0) is also 0.55-API tied.
-- hyprglass is back on v0.8.1 (built against 0.56.2 by hyprland/overlay.nix) and is
-- loaded + configured from the start hook below: a plugin cannot be dlopen'd while
-- this file is still being parsed, and the plugin's own Lua config API aborts the
-- compositor (SIGABRT in forwardLuaConfig), so the settings live in
-- files/gui/hypr/hyprglass.lua and are pushed as plain config keys by the generated
-- hyprglass-setup helper. hy3/hyprspace stay dropped — their 0.55 compositor API no
-- longer compiles against 0.56.

-- ---------------------------------------------------------------------
-- Visual variables (from vars.conf)
-- ---------------------------------------------------------------------
local border_size            = 0 -- frameless: no window borders at all
local col_border_active_base = "rgba(00285981)"
local col_border_inactive    = "rgba(00000000)"
local rounding               = 0
local rounding_power         = 0
local opacity_active         = 1.0
local opacity_inactive       = 1.0
local blur_size              = 26 -- was 9; the bar/panels dropped hyprglass's 36px layer blur
local blur_passes            = 4  -- was 2; those surfaces rely on Hyprland's own blur now,
                               -- (hyprglass glasses only windows + popups now), so the
                               -- knobs here are the bar's blur strength.
local blur_vibrancy          = 0.1696

-- ---------------------------------------------------------------------
-- Common window matcher regexes (from vars.conf / classes.conf)
-- NOTE: in Lua strings "\\." == regex "\." (a literal dot)
-- ---------------------------------------------------------------------
local m = {
  browser            = "^([Vv]ivaldi-stable|[Vv]ivaldi)$",
  file_dialog        = "^(Open File|Select a File|Choose wallpaper|Open Folder|Save As|Library|File Upload)(.*)$",
  pip                = "^([Pp]icture[-\\s]?[Ii]n[-\\s]?[Pp]icture)(.*)$",
  telegram_wrapped   = "^(.telegram-desktop-wrapped)$",
  telegram_org       = "^(org\\.telegram.desktop)$",
  utility            = "^(qt5ct|wine|steamwebhelper|sun-awt-X11-XFramePeer|xdg-desktop-portal-gtk)$",
  steam_app          = "^(steam_app)",
  xwaylandvideobridge = "^(xwaylandvideobridge)$",
  -- scratchpad classes
  im_scratchpad      = "^(KotatogramDesktop|Skype|Slack|TelegramDesktop|org\\.telegram\\.desktop|zoom)$",
  music_scratchpad   = "^(ncmpcpp|rmpc|music)$",
  mail_scratchpad    = "^(mutterfox|neomutt)$",
  mixer_scratchpad   = "^(ncpamixer|com\\.saivert\\.pwvucontrol)$",
  torrment_scratchpad = "^(torrment)$",
  rebuild_scratchpad = "^(rebuild)$",
  teardown_scratchpad = "^(teardown)$",
}

-- Workspace routing classes (from classes.conf)
local cls = {
  term        = "^(term)$",
  web         = "^([Vv]ivaldi-stable|[Vv]ivaldi)$",
  dev         = "^(nwim)$",
  games       = "^(steam|Steam)$",
  doc         = "^(sioyek)$",
  vid         = "^(mpv)$",
  obs         = "^(obs)$",
  -- swayimg (fork) appends "_<pid>" to app_id when overlay mode is enabled
  -- (files/gui/swayimg/init.lua: swayimg.enable_overlay(true)), so allow the suffix.
  pic         = "^swayimg(_[0-9]+)?$",
  vm          = "^(.virt-manager-wrapped|qemu-system-x86_64|Qemu-system-x86_64)$",
  wine        = "^(com.usebottles.bottles)$",
  daw         = "^(Renoise)$",
  vital       = "^(Vital)$",
  dw          = "^(org.nicotine_plus.Nicotine)$",
  keyboard    = "^(Bazecor|wootility-lekker|Vial|via)$",
  im          = "^(im.riot.Riot)$",
  remote      = "^(Vmware-view|xfreerdp|remmina|org.remmina.Remmina)$",
  notes       = "^(Obsidian)$",
}

-- ---------------------------------------------------------------------
-- Monitors (from init.conf)
-- ---------------------------------------------------------------------
hl.monitor({ output = "DP-2", mode = "3840x2160@240", position = "0x0", scale = 2, vrr = 1, bitdepth = 10, cm = "auto" })
hl.monitor({ output = "DP-1", disabled = true })
-- DP-4: second cable (motherboard iGPU) to the same MPG321UX panel — a phantom
-- 4K60 screen that only shows if the monitor OSD input is switched. Keep disabled.
hl.monitor({ output = "DP-4", disabled = true })

-- ---------------------------------------------------------------------
-- VRR: games only
-- ---------------------------------------------------------------------
-- Adaptive sync lets the panel refresh follow the frame pacing, which is what
-- makes the rate visibly twitch during ordinary work, and it is the one thing
-- games genuinely want. The policy from the misc block therefore stays off and
-- is switched on only while a game window exists. Enabling it means flipping
-- `misc.vrr` at runtime (the Lua API's hl.config, which applies live) rather
-- than a static value, so nothing else needs to be toggled per game.
local VRR_GAME_CLASSES = { "^steam_app_", "^osu!$", "^cs2$", "^gamescope" }

local function isGameClass(class)
  if not class then return false end
  for _, pattern in ipairs(VRR_GAME_CLASSES) do
    if class:match(pattern) then return true end
  end
  return false
end

-- Counted from the live window list rather than with a counter: a window can
-- disappear without a `close` event (kill, crash), and a counter would then keep
-- VRR on for the rest of the session.
local function gamesOpen()
  local n = 0
  for _, win in ipairs(hl.get_windows()) do
    if isGameClass(win.class) then n = n + 1 end
  end
  return n
end

local vrrState = nil
local function applyVrr()
  local on = gamesOpen() > 0
  if on == vrrState then return end -- no point pushing the same value again
  vrrState = on
  hl.config({ misc = { vrr = on and 1 or 0 } })
end

-- A reload with a game already mapped must not lose VRR.
applyVrr()

-- The window list settles a moment after the event (a closing window may still be
-- in it while the handler runs), so the recount is deferred as well as immediate.
local function vrrOnWindowChange()
  applyVrr()
  hl.timer(applyVrr, { timeout = 300, type = "oneshot" })
end

for _, event in ipairs({ "window.open", "window.close", "window.destroy" }) do
  hl.on(event, vrrOnWindowChange)
end

-- ---------------------------------------------------------------------
-- hyprglass: put the settings back after anything that drops them
-- ---------------------------------------------------------------------
-- The plugin holds its config only until something re-initialises its state: a
-- `hyprctl reload` drops it back to the plugin defaults (blur_strength 2,
-- vibrancy -1, glass_opacity 1) while the files still say otherwise.
--
-- `config.reloaded` sounds like the hook for that, but it does not fire for a
-- compositor reload (measured: a file-writing handler stayed empty across
-- `hyprctl reload`), so the repair lives in a timer instead — see
-- hyprglass-watch in modules/user/nix-maid. The session start is still worth
-- hooking here, and `hyprglass-apply` checks its work instead of assuming it.
hl.on("hyprland.start", function()
  hl.exec_cmd("hyprglass-apply >/dev/null 2>&1 || true")
end)

-- ---------------------------------------------------------------------
-- Environment (from env.conf)
-- ---------------------------------------------------------------------
hl.env("CLUTTER_BACKEND", "wayland")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
hl.env("GDK_BACKEND", "wayland")
hl.env("GDK_SCALE", "2")
hl.env("MOZ_ENABLE_WAYLAND", "1")
hl.env("QML_XHR_ALLOW_FILE_READ", "1")
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
hl.env("QT_ENABLE_HIGHDPI_SCALING", "1")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("QT_STYLE_OVERRIDE", "kvantum")
hl.env("QT_XDG_DESKTOP_PORTAL", "1")
hl.env("SDL_VIDEODRIVER", "wayland,x11")
hl.env("XCURSOR_SIZE", "23")
hl.env("XCURSOR_THEME", "Alkano-aio")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")

-- ---------------------------------------------------------------------
-- Core configuration (from init.conf) -- master layout
-- ---------------------------------------------------------------------
hl.config({
  general = {
    gaps_in = 0, gaps_out = 0, border_size = border_size,
    col = {
      active_border = { colors = { col_border_active_base, col_border_active_base }, angle = 45 },
      inactive_border = col_border_inactive,
    },
    resize_on_border = false, allow_tearing = true, layout = "master",
  },
  decoration = {
    rounding = rounding, rounding_power = rounding_power,
    active_opacity = opacity_active, inactive_opacity = opacity_inactive,
    shadow = { enabled = false }, -- frameless: the compositor never draws a shadow here
    -- xray: sample what is *behind* the surface and ignore whatever sits between
    -- it and the wallpaper (the same idea as the xray layer rule further down).
    -- Without it a stacked layer re-blurs an already blurred window underneath,
    -- which is what made the bar/panel blur muddy against hyprglass windows.
    blur = { enabled = true, size = blur_size, passes = blur_passes, vibrancy = blur_vibrancy, xray = true },
    -- motion blur: adds a smear while anything on screen is moving — the
    -- scrolling tape and dragged windows are where it reads. 24 samples is the
    -- tuning knob (higher = smoother, more GPU); `hyprctl eval 'hl.config({
    -- decoration = { motion_blur = { enabled = false } } })' turns it off live.
    motion_blur = { enabled = true, samples = 24 },
    dim_special = false,
  },
  input = {
    -- Keyboard layouts: `us` MUST stay first. Binds are resolved against the FIRST
    -- layout (input:resolve_binds_by_sym = false is the default), so `us,ru` keeps
    -- every bind working in both layouts. Switching: M4+S.
    kb_layout = "us,ru", kb_variant = "", kb_model = "", kb_options = "", kb_rules = "",
    resolve_binds_by_sym = false,
    follow_mouse = 1, sensitivity = 0, repeat_rate = 35, repeat_delay = 250,
    touchpad = { natural_scroll = true, disable_while_typing = true, clickfinger_behavior = true },
  },
  misc = {
    disable_hyprland_logo = false, enable_anr_dialog = false, force_default_wallpaper = 0,
    font_family = "Iosevka", splash_font_family = "Iosevka",
    -- VRR is driven per game window, see the block after the monitor rules:
    -- "fullscreen only" (2) still left the output in adaptive-sync mode for the
    -- whole session, and the panel refresh then twitched along with the frame
    -- pacing while working.
    vrr = 0, disable_autoreload = 1,
    -- Motion for actions Hyprland would otherwise snap: manual resizes and
    -- mouse window dragging both replay through the windowsMove spring.
    animate_manual_resizes = true, animate_mouse_windowdragging = true,
  },
  cursor = {
    sync_gsettings_theme = true, min_refresh_rate = 175, inactive_timeout = 0,
    hide_on_key_press = true, warp_on_change_workspace = false,
  },
  -- new_render_scheduling: 0.56's alternative frame scheduler (the old one is
  -- still the default). Reverting needs no reload — in a live session
  -- `hyprctl keyword render:new_render_scheduling false` is enough.
  render = { direct_scanout = 2, new_render_scheduling = true },
  xwayland = { force_zero_scaling = true, use_nearest_neighbor = true },
  master = { new_status = "master", mfact = 0.6, orientation = "left", allow_small_split = true, smart_resizing = true },
})

-- Screencopy and permissions now handled natively by Hyprland Lua API

-- =====================================================================
-- Keybindings (from bindings.conf and bindings/*)
-- =====================================================================
local M4 = "SUPER"
local M1 = "ALT"
local C  = "CTRL"
local SH = "SHIFT"

local browser = "vivaldi"
local menu    = "vicinae toggle"

-- --- Top-level binds (bindings.conf) ---
-- Use "all" (not "current"): kanata's virtual keyboard is the last active
-- device, so "current" switches only it and the bar/typing layouts diverge.
hl.bind(M4 .. "+S", hl.dsp.exec_cmd("hyprctl switchxkblayout all next"))
hl.bind(M1 .. "+Tab", hl.dsp.focus({ workspace = "previous" }))
hl.bind(M4 .. "+slash", hl.dsp.focus({ workspace = "previous" }))
hl.bind(M4 .. "+" .. C .. "+backslash", hl.dsp.window.resize({ x = 640, y = 480 }))
hl.bind(M4 .. "+Tab", hl.dsp.window.cycle_next({ next = true }))
hl.bind(M4 .. "+c", hl.dsp.exec_cmd("vicinae deeplink vicinae://launch/clipboard/history"))
hl.bind(M4 .. "+Escape", hl.dsp.window.close())
hl.bind(M4 .. "+r", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
-- Pseudo-fullscreen (maximize) toggle: fills the work area but stays a normal
-- window (bar stays on top) — the same state swayimg gets from the
-- "pic-pseudo-fullscreen" rule, and the only fullscreen-ish toggle for it.
hl.bind(M4 .. "+" .. SH .. "+f", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }))
hl.bind(M4 .. "+Return", hl.dsp.exec_cmd("kitty"), { locked = true })
-- pass-2col: pick a password/OTP entry from the pass store via vicinae dmenu
hl.bind(M4 .. "+p", hl.dsp.exec_cmd("pass-2col"), { locked = true })
hl.bind(M4 .. "+mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(M4 .. "+mouse_up", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(M4 .. "+mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(M4 .. "+mouse:273", hl.dsp.window.resize(), { mouse = true })

-- --- Scratchpads (sashetophizika/hyprscratch with special workspace) ---
hl.bind(M4 .. "+d", hl.dsp.exec_cmd("hyprscratch teardown 'kitty-glass --class teardown -e btop' special"))
hl.bind(M4 .. "+e", hl.dsp.exec_cmd("hyprscratch toggle telegram"))
hl.bind(M4 .. "+f", hl.dsp.exec_cmd("hyprscratch music 'kitty-glass --class music -e rmpc' special"))
hl.bind(M4 .. "+t", hl.dsp.exec_cmd("hyprscratch torrment 'kitty-glass --class torrment -e rustmission' special"))
hl.bind(M4 .. "+u", hl.dsp.exec_cmd("hyprscratch vpn 'kitty-glass --class vpn -e tun status' special"))
hl.bind(M4 .. "+" .. C .. "+p", hl.dsp.exec_cmd("hyprscratch mixer 'kitty-glass --class mixer -e ncpamixer' special"))
hl.bind(M4 .. "+" .. SH .. "+h", hl.dsp.exec_cmd("hyprscratch hide-all"))
-- --- Overview (hyprexpo) ───────────────────────────────────────────────
-- The dispatcher goes through hyprctl eval on purpose: hyprexpo is dlopen'd by
-- the hyprexpo-setup helper at session start, i.e. after this file is parsed, so
-- hl.plugin.hyprexpo is still nil *here* (same constraint as hyprglass). In Lua
-- config mode `hyprctl dispatch X` is only a deprecated shorthand and mangles
-- plugin dispatchers ("expected a dispatcher"), so the runtime Lua namespace is
-- used instead — verified in a nested 0.56.2 instance.

hl.bind(M4 .. "+grave", hl.dsp.exec_cmd([[hyprctl eval 'hl.plugin.hyprexpo.expo("toggle")']]))

-- --- Window shaders (HyprWindowShade) ──────────────────────────────────
-- Plugin functions live under hl.plugin.HyprWindowShade.* only *after* the .so
-- is dlopen'd by hyprwindowshade-setup (session start, i.e. after this file is
-- parsed), so every bind looks the namespace up at keypress time — the pattern
-- the plugin's own README prescribes. That also keeps the bind alive when the
-- plugin failed to load, and says so instead of failing silently.
-- SHADERS mirrors files/gui/hypr/hyprwindowshade.lua.
local SHADERS = (os.getenv("HOME") or "") .. "/.config/hypr/shaders/"

local shade_ns = function()
  local ns = hl.plugin.HyprWindowShade
  if not ns then
    hl.notification.create({
      text = "[HyprWindowShade] plugin not loaded",
      timeout = 3000,
      color = "rgb(ff5555)",
    })
  end
  return ns
end

-- Obscure the focused window (pixelate); press again to clear it.
hl.bind(M4 .. "+" .. SH .. "+x", function()
  local ns = shade_ns()
  if ns then ns.togglewindowshader(SHADERS .. "pixelate.glsl") end
end)

-- Strip every shader from the focused window (undo).
hl.bind(M4 .. "+" .. SH .. "+u", function()
  local ns = shade_ns()
  if ns then ns.togglewindowshader("clear") end
end)

-- --- App launchers (ex-apps.conf; formerly ~/.config/hypr/bindings/apps.conf) ---
hl.bind(M4 .. "+w", hl.dsp.exec_cmd('raise --match "class:regex=' .. m.browser .. '" --launch ' .. browser))
hl.bind(M4 .. "+x", hl.dsp.exec_cmd('raise --match "class:regex=^term$" --launch "kitty --class term"'))
hl.bind(M4 .. "+q", hl.dsp.exec_cmd('raise --match "class:regex=^nwim$" --launch "kitty --class nwim -e /home/neg/.local/bin/v"'))
hl.bind(M4 .. "+b", hl.dsp.exec_cmd('raise --match "class:regex=^mpv$" --launch "~/.local/bin/pl video"'))
hl.bind(M4 .. "+" .. C .. "+c", hl.dsp.exec_cmd('raise --match "class:regex=^swayimg(_[0-9]+)?$" --launch "swayimg ~/dw"'))
hl.bind(M4 .. "+" .. SH .. "+c", hl.dsp.exec_cmd("wl random ~/pic/wl"))

-- --- System ────────────────────────────────────────────────────────────
hl.bind(M4 .. "+" .. SH .. "+n", hl.dsp.exec_cmd("hyprscratch rebuild 'kitty-glass --class rebuild -e nh os switch /etc/nixos#odin --option substitute false' special"))
hl.bind(M4 .. "+" .. C .. "+v", hl.dsp.exec_cmd('raise --match "class:regex=^Bazecor$" --launch "bazecor"'))
hl.bind(M4 .. "+g", hl.dsp.exec_cmd('raise --match "class:regex=^(steam|com\\.valvesoftware\\.Steam|steam_app.*|gamescope)$" --launch "steam"'))
hl.bind(M4 .. "+" .. C .. "+o", hl.dsp.exec_cmd('raise --match "class:regex=^(obs|com\\.obsproject\\.Studio)$" --launch "obs"'))
hl.bind(M4 .. "+" .. C .. "+n", hl.dsp.exec_cmd('raise --match "class:regex=^(Obsidian|md\\.obsidian\\.Obsidian)$" --launch "obsidian"'))

-- --- Media (media.conf) ---
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("genlc-media up; swayosd-client --output-volume +5"), { repeating = true, locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("genlc-media down; swayosd-client --output-volume -5"), { repeating = true, locked = true })
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("swayosd-client --output-volume +5; genlc-media up"), { repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("swayosd-client --output-volume -5; genlc-media down"), { repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("swayosd-client --output-volume mute-toggle; genlc-media mute"), { repeating = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("swayosd-client --input-volume mute-toggle"), { repeating = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("swayosd-client --brightness +10"), { repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("swayosd-client --brightness -10"), { repeating = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind(M4 .. "+" .. SH .. "+w", hl.dsp.exec_cmd("~/.local/bin/pl cmd play-pause"), { locked = true })
hl.bind(M4 .. "+comma", hl.dsp.exec_cmd("~/.local/bin/pl cmd previous"), { locked = true })
hl.bind(M4 .. "+period", hl.dsp.exec_cmd("~/.local/bin/pl cmd next"), { locked = true })
hl.bind(M4 .. "+" .. SH .. "+i", hl.dsp.exec_cmd("~/.local/bin/pl vol mute"), { locked = true })
hl.bind(M4 .. "+" .. SH .. "+o", hl.dsp.exec_cmd("~/.local/bin/pl vol unmute"), { locked = true })
hl.bind(M4 .. "+m", hl.dsp.exec_cmd("~/.local/bin/music-rename current"), { locked = true })

-- Euphonica (GTK4/libadwaita MPD client) — run-or-raise, the GUI counterpart
-- to the M4+f rmpc scratchpad.
hl.bind(M4 .. "+" .. SH .. "+e", hl.dsp.exec_cmd('raise --match "class:regex=^(euphonica|io\\.github\\.htkhiem\\.Euphonica)$" --launch "euphonica"'), { locked = true })
-- MPD transport mode (submap below): ncmpcpp/rmpc letters for the verbs MPRIS
-- does not carry (repeat/random/single/consume, relative seek, software volume).
hl.bind(M4 .. "+" .. SH .. "+p", hl.dsp.submap("music"))

-- --- Misc (misc.conf) ---
hl.bind(M1 .. "+g", hl.dsp.exec_cmd("vicinae deeplink vicinae://launch/wm/switch-windows"))

-- hyprwhspr-rs dictation: hold ALT+` to talk (released fires on key up)
hl.bind(M1 .. "+GRAVE", hl.dsp.exec_cmd("hyprwhspr-rs record start"))
hl.bind(M1 .. "+GRAVE", hl.dsp.exec_cmd("hyprwhspr-rs record stop"), { release = true })
-- One search window for the tray/app menus (StatusNotifierItem DBusMenus, submenus
-- included) *and* the main-menu helper actions — menu-search lists both and fires
-- the chosen entry. Replaces the bare main-menu picker on this hotkey.
hl.bind(M4 .. "+" .. SH .. "+m", hl.dsp.exec_cmd("menu-search"), { locked = true })
hl.bind(M4 .. "+" .. SH .. "+r", hl.dsp.exec_cmd('shot="$HOME/pic/shots/satty-$(date \'+%Y%m%d-%H.%M.%S\').png"; grim -l 0 "$shot" && pic-info "$shot"'))
hl.bind(M4 .. "+" .. SH .. "+" .. C .. "+r", hl.dsp.exec_cmd('shot="$HOME/pic/shots/satty-$(date \'+%Y%m%d-%H.%M.%S\').png"; grim -l 0 -g "$(slurp)" "$shot" && pic-info "$shot"'))
hl.bind(M4 .. "+" .. SH .. "+v", hl.dsp.exec_cmd("~/.local/bin/screenrec screen"))
hl.bind(M4 .. "+" .. SH .. "+" .. C .. "+v", hl.dsp.exec_cmd("~/.local/bin/screenrec area"))
-- Screen annotation overlay (wayscriber): toggle the resident drawing layer
hl.bind(M4 .. "+" .. SH .. "+z", hl.dsp.exec_cmd("wayscriber --daemon-toggle"), { locked = true })
-- Synths: run-or-raise via packages/local-bin/bin/synth (VSTPlugin in SC / yabridge)
hl.bind(M4 .. "+" .. SH .. "+s", hl.dsp.exec_cmd("synth Surge_XT"))
hl.bind(M4 .. "+" .. SH .. "+l", hl.dsp.exec_cmd("synth LegendHZ"))
hl.bind(M4 .. "+" .. SH .. "+t", hl.dsp.exec_cmd("sc-live")) -- raw SuperCollider live-coding scene (scnvim)
-- Renoise tracker (workspace 12 "daw"): run-or-raise via the raise helper
hl.bind(M4 .. "+" .. SH .. "+a", hl.dsp.exec_cmd('raise --match "class:regex=^(Renoise)$" --launch "renoise"'))
hl.bind(M1 .. "+q", hl.dsp.exec_cmd(menu))
hl.bind("Caps_Lock", hl.dsp.exec_cmd("swayosd-client --caps-lock"))
hl.bind(M4 .. "+apostrophe", hl.dsp.exec_cmd("hypr-fix"))

-- --- Notifications (quickshell notification center) ---
hl.bind(M4 .. "+n", hl.dsp.exec_cmd("quickshell ipc call globalIPC toggleNotificationCenter"))
-- Glass panel: live tuning for the hyprglass settings (see the panel module and
-- hyprglass-apply). Next to the notification centre bind, same IPC shape.
hl.bind(M4 .. "+" .. SH .. "+g", hl.dsp.exec_cmd("quickshell ipc call globalIPC toggleGlassPanel"))
hl.bind(M4 .. "+space", hl.dsp.exec_cmd("touch $HOME/.cache/quickshell/notif-close-all"), { locked = true })

-- --- Overlay dismissal (quickshell widgets) ---
-- Global fallback: M4+Escape or M4+Shift+K / M4+Shift+D
hl.bind(M4 .. "+" .. SH .. "+k", hl.dsp.exec_cmd("touch $HOME/.cache/quickshell/dismiss-overlay"))
hl.bind(M4 .. "+" .. SH .. "+d", hl.dsp.exec_cmd("touch $HOME/.cache/quickshell/dismiss-overlay"))



-- --- Split ratio helpers (tiling-helpers.conf) ---
hl.bind(M4 .. "+" .. C .. "+d", hl.dsp.layout("splitratio -0.1"), { repeating = true })
hl.bind(M4 .. "+" .. C .. "+f", hl.dsp.layout("splitratio +0.1"), { repeating = true })

-- =====================================================================
-- Emacs-style navigation (additive layer)
-- =====================================================================
-- Super+Alt acts as the "Meta" prefix so nothing collides with app-level
-- Ctrl shortcuts or the existing vim-style M4+h/j/k/l binds.
-- Mirrors Emacs/EXWM muscle memory:
--   C-n/C-p/C-f/C-b  move focus down/up/right/left (like Emacs point moves)
--   C-a/C-e          first/last workspace        (like beginning/end of line)
--   C-o              other window                (like C-x o)
--   C-<Tab>          switch window               (like C-x b switch-to-buffer)
--   C-x              open vicinae command menu   (like M-x)
--   C-1..C-9/C-0     jump to workspace 1..10     (like digit-argument)
--   C-- / C-=        previous / next workspace
local E = M4 .. "+" .. M1

hl.bind(E .. "+n", hl.dsp.focus({ direction = "down" }))
hl.bind(E .. "+p", hl.dsp.focus({ direction = "up" }))
hl.bind(E .. "+f", hl.dsp.focus({ direction = "right" }))
hl.bind(E .. "+b", hl.dsp.focus({ direction = "left" }))
hl.bind(E .. "+a", hl.dsp.focus({ workspace = "1" }))
hl.bind(E .. "+e", hl.dsp.focus({ workspace = "19" }))
hl.bind(E .. "+o", hl.dsp.window.cycle_next({ next = true }))
hl.bind(E .. "+Tab", hl.dsp.exec_cmd("vicinae deeplink vicinae://launch/wm/switch-windows"))
hl.bind(E .. "+x", hl.dsp.exec_cmd(menu))
for _, i in ipairs({ 1, 2, 3, 4, 5, 6, 7, 8, 9 }) do
  hl.bind(E .. "+" .. tostring(i), hl.dsp.focus({ workspace = tostring(i) }))
end
hl.bind(E .. "+minus", hl.dsp.focus({ workspace = "previous" }))
hl.bind(E .. "+equal", hl.dsp.focus({ workspace = "e+1" }))

-- =====================================================================
-- Submaps (bindings/_resets.conf and submap files)
-- =====================================================================
local function submap_resets()
  hl.bind("escape", hl.dsp.submap("reset"))
  hl.bind(C .. "+c", hl.dsp.submap("reset"))
  hl.bind(C .. "+q", hl.dsp.submap("reset"))
  hl.bind("q", hl.dsp.submap("reset"))
end


local function binde_reset(key, fn)
  hl.bind(key, fn, { repeating = true })
  hl.bind(key, hl.dsp.submap("reset"), { repeating = true })
end

-- Submap: resize (resize.conf)
hl.bind(M4 .. "+" .. M1 .. "+r", hl.dsp.submap("resize"))
hl.define_submap("resize", "reset", function()
  submap_resets()
  hl.bind("right", hl.dsp.window.resize({ x = 10, y = 0, relative = true }), { repeating = true })
  hl.bind("left",  hl.dsp.window.resize({ x = -10, y = 0, relative = true }), { repeating = true })
  hl.bind("up",    hl.dsp.window.resize({ x = 0, y = -10, relative = true }), { repeating = true })
  hl.bind("down",  hl.dsp.window.resize({ x = 0, y = 10, relative = true }), { repeating = true })
  hl.bind("l", hl.dsp.window.resize({ x = 10, y = 0, relative = true }), { repeating = true })
  hl.bind("h", hl.dsp.window.resize({ x = -10, y = 0, relative = true }), { repeating = true })
  hl.bind("k", hl.dsp.window.resize({ x = 0, y = -10, relative = true }), { repeating = true })
  hl.bind("j", hl.dsp.window.resize({ x = 0, y = 10, relative = true }), { repeating = true })
  hl.bind(SH .. "+l", hl.dsp.window.resize({ x = -10, y = 0, relative = true }), { repeating = true })
  hl.bind(SH .. "+h", hl.dsp.window.resize({ x = 10, y = 0, relative = true }), { repeating = true })
  hl.bind(SH .. "+k", hl.dsp.window.resize({ x = 0, y = 10, relative = true }), { repeating = true })
  hl.bind(SH .. "+j", hl.dsp.window.resize({ x = 0, y = -10, relative = true }), { repeating = true })
  hl.bind("Return", hl.dsp.submap("reset"))
end)

-- Submap: special (special.conf)
hl.bind(M1 .. "+e", hl.dsp.submap("special"))
hl.define_submap("special", "reset", function()
  submap_resets()
  binde_reset("d", hl.dsp.exec_cmd('raise --match "class:regex=^org\\.nicotine_plus\\.Nicotine$" --launch "nicotine"'))
  binde_reset(SH .. "+l", hl.dsp.exec_cmd("hyprctl switchxkblayout all 0")) -- hyprlock temporarily disabled (2026-08-31)
  binde_reset("e", hl.dsp.window.float({ action = "toggle" }))
  binde_reset("f", hl.dsp.window.fullscreen_state({ internal = 0, client = 3, action = "toggle" }))
  binde_reset("z", hl.dsp.window.fullscreen_state({ internal = 0, client = 3, action = "toggle" }))
  hl.bind("semicolon", hl.dsp.submap("reset"), { repeating = true })
  binde_reset(SH .. "+w", hl.dsp.exec_cmd("pkill iwmenu || iwmenu"))
  binde_reset("o", hl.dsp.exec_cmd('raise --match "title:regex=' .. m.file_dialog .. '"'))
end)


-- Submap: wallpaper (wallpaper.conf)
hl.bind(M4 .. "+" .. SH .. "+y", hl.dsp.submap("wallpaper"))
hl.define_submap("wallpaper", "reset", function()
  submap_resets()
  hl.bind("y", hl.dsp.exec_cmd("wl random ~/pic/wl"))
  hl.bind(M4 .. "+y", hl.dsp.exec_cmd("wl random ~/pic/wl"))
  hl.bind(SH .. "+w", hl.dsp.submap("reset"))
end)

-- Submap: tiling (tiling.conf)
hl.bind(M4 .. "+minus", hl.dsp.submap("tiling"))
hl.define_submap("tiling", "reset", function()
  submap_resets()
  hl.bind(SH .. "+h", hl.dsp.window.move({ direction = "l" }))
  hl.bind(SH .. "+j", hl.dsp.window.move({ direction = "d" }))
  hl.bind(SH .. "+k", hl.dsp.window.move({ direction = "u" }))
  hl.bind(SH .. "+l", hl.dsp.window.move({ direction = "r" }))
end)

-- Submap: music (MPD transport with ncmpcpp/rmpc letter bindings)
-- mpc drives MPD directly: playerctl/mpdris2 relays only play-pause and skips,
-- while repeat/random/single/consume, relative seek and the MPD software mixer
-- (mixer_type "software" in mpd.conf) exist only on the MPD protocol.
-- Letters follow the rmpc config (files/rmpc/config.ron) and ncmpcpp:
--   p/space toggle   s stop   n/N next/prev (also ,/.)
--   b/f seek -/+10s  h/l seek -/+5s
--   z repeat  r random  y single  R consume  u update  U rescan
--   -/= MPD volume   e Euphonica
hl.define_submap("music", "reset", function()
  submap_resets()
  hl.bind(M4 .. "+" .. SH .. "+p", hl.dsp.submap("reset"))
  hl.bind("p", hl.dsp.exec_cmd("mpc toggle"))
  hl.bind("space", hl.dsp.exec_cmd("mpc toggle"))
  hl.bind("s", hl.dsp.exec_cmd("mpc stop"))
  hl.bind("n", hl.dsp.exec_cmd("mpc next"))
  hl.bind("N", hl.dsp.exec_cmd("mpc prev"))
  hl.bind("comma", hl.dsp.exec_cmd("mpc prev"))
  hl.bind("period", hl.dsp.exec_cmd("mpc next"))
  hl.bind("b", hl.dsp.exec_cmd("mpc seek -10"), { repeating = true })
  hl.bind("f", hl.dsp.exec_cmd("mpc seek +10"), { repeating = true })
  hl.bind("h", hl.dsp.exec_cmd("mpc seek -5"), { repeating = true })
  hl.bind("l", hl.dsp.exec_cmd("mpc seek +5"), { repeating = true })
  hl.bind("minus", hl.dsp.exec_cmd("mpc volume -5"), { repeating = true })
  hl.bind("equal", hl.dsp.exec_cmd("mpc volume +5"), { repeating = true })
  hl.bind("z", hl.dsp.exec_cmd("mpc repeat"))
  hl.bind("r", hl.dsp.exec_cmd("mpc random"))
  hl.bind("y", hl.dsp.exec_cmd("mpc single"))
  hl.bind("R", hl.dsp.exec_cmd("mpc consume"))
  hl.bind("u", hl.dsp.exec_cmd("mpc update"))
  hl.bind("U", hl.dsp.exec_cmd("mpc rescan"))
  hl.bind("e", hl.dsp.exec_cmd('raise --match "class:regex=^(euphonica|io\\.github\\.htkhiem\\.Euphonica)$" --launch "euphonica"'))
end)

-- =====================================================================
-- Workspaces (workspaces.conf / workspaces.nix)
-- =====================================================================
local workspaces = {
  { id = 1,  name = "𐌰:term",   layout = "scrolling" },
  { id = 2,  name = "𐌱:web",    layout = "scrolling" },
  { id = 3,  name = "𐌲:dev",    layout = "scrolling" },
  { id = 4,  name = "𐌸:games" }, -- master (gaming)
  { id = 5,  name = "𐌳:doc",    layout = "scrolling" },
  { id = 6,  name = "𐌵:vid" },  -- master (media)
  { id = 7,  name = "𐌶:obs" },  -- master (media)
  { id = 8,  name = "𐌷:pic",    layout = "scrolling" },
  { id = 9,  name = "𐌺:vm",     layout = "scrolling" },
  { id = 10, name = "𐌻:wine" }, -- master (wine/games)
  { id = 12, name = "𐌽:daw" },  -- master (media/audio)
  { id = 13, name = "𐌾:dw",     layout = "scrolling" },
  { id = 14, name = "𐌿:keyboard", layout = "scrolling" },
  { id = 15, name = "𐍀:im",     layout = "scrolling" },
  { id = 16, name = "𐍁:remote", layout = "scrolling" },
  { id = 17, name = "Ⲣ:notes",   layout = "scrolling" },
  { id = 18, name = "𐍆:vital" }, -- Vital standalone synth
  { id = 19, name = "𐍇:rack", layout = "scrolling" }, -- VCV Rack modular synth (GLFW)
}

for _, w in ipairs(workspaces) do
  local rule = { workspace = tostring(w.id), default_name = w.name }
  if w.layout then rule.layout = w.layout end
  hl.workspace_rule(rule)
end

-- Special on-screen workspaces (TV / fullscreen game), no gaps
hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
hl.workspace_rule({ workspace = "f[1]", gaps_out = 0, gaps_in = 0 })

-- =====================================================================
-- Scrolling layout (core since 0.55 — no plugin; the `layout = "scrolling"`
-- workspace rules above select it per workspace)
-- =====================================================================
hl.config({
  scrolling = {
    column_width = 0.6, -- Denial-style: the focused column is a bit wider than half the screen
    focus_fit_method = 0, -- 0 = keep the focused column centered (1 = fit it into view)
    follow_focus = true,
    follow_min_visible = 0.4,
    direction = "right", -- new windows land to the right, the tape scrolls right
    wrap_focus = true,
    wrap_swapcol = true,
    explicit_column_widths = "0.333, 0.5, 0.667, 1.0", -- cycled by colresize +conf/-conf
  },
})

-- Trackpad: 3-finger swipe switches workspaces.
-- NOTE: only ONE horizontal gesture can exist — Hyprland keys the gesture table on
-- the direction alone, so a second horizontal entry (e.g. 4-finger scroll_move for
-- the scrolling tape) is silently shadowed by the first ("Gesture will be
-- overshadowed by a previous gesture"). The tape is scrolled with M4+[ / M4+].
hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })
hl.gesture({ fingers = 3, direction = "down", mods = "ALT", action = "close" })

-- Scrolling binds — brackets (free keys; M4+comma/period are the player)
hl.bind(M4 .. "+bracketright", hl.dsp.layout("move +col"), { repeating = true })
hl.bind(M4 .. "+bracketleft", hl.dsp.layout("move -col"), { repeating = true })
hl.bind(M4 .. "+" .. SH .. "+bracketright", hl.dsp.layout("swapcol r"))
hl.bind(M4 .. "+" .. SH .. "+bracketleft", hl.dsp.layout("swapcol l"))
hl.bind(M4 .. "+" .. C .. "+bracketright", hl.dsp.layout("colresize +conf"), { repeating = true })
hl.bind(M4 .. "+" .. C .. "+bracketleft", hl.dsp.layout("colresize -conf"), { repeating = true })
hl.bind(M4 .. "+" .. M1 .. "+bracketright", hl.dsp.layout("promote")) -- window into its own column
hl.bind(M4 .. "+" .. M1 .. "+bracketleft", hl.dsp.layout("fit_into_view"))
hl.bind(M4 .. "+left", hl.dsp.focus({ direction = "left" }))
hl.bind(M4 .. "+right", hl.dsp.focus({ direction = "right" }))

-- Terminal columns start narrow (other windows use the 0.6 default)
hl.window_rule({ name = "scrolling-term-width", match = { class = "^(term|nwim)$" }, scrolling_width = 0.5 })

-- =====================================================================
-- Animations
-- =====================================================================
-- Only the curves that are actually referenced below are declared; Hyprland
-- ships `default` itself, and beziers nothing points at are dead weight:
--   menu_decel / menu_accel -> the layer leaves (the only bezier leaves left)
--   spring_crisp            -> windows, fades
--   spring_glide            -> long travel: the scrolling tape, workspaces
hl.curve("menu_decel",    { type = "bezier", points = { {0.1, 1}, {0, 1} } })
hl.curve("menu_accel",    { type = "bezier", points = { {0.38, 0.04}, {1, 0.07} } })

-- Spring curves: physics-based easing (mass 1; stiffness sets the pace, dampening
-- the bounce). Same model Denial uses for its shell (Flutter SpringDescription).
-- `dampening` is the accepted spelling — the official example's "damping" fails to
-- parse. Both are critically damped (dampening = 2*sqrt(stiffness)), so the motion
-- ends sharply and never overshoots.
--
-- A spring ignores the leaf's duration and is advanced by real frame time
-- (hyprutils advanceSpring, OMEGA0 = sqrt(stiffness/mass)), so stiffness is the
-- only knob: critically damped settle is 4.6/OMEGA0, i.e. ~77 ms here (~87 ms on
-- the glide curve). Stiffness x4 = 2x faster, dampening x2 keeps ratio 1.0.
hl.curve("spring_crisp",  { type = "spring", mass = 1, stiffness = 3600, dampening = 120 })
hl.curve("spring_glide",  { type = "spring", mass = 1, stiffness = 2800, dampening = 105.83 })

-- NOTE: the schema requires `speed` (> 0) on every leaf, even a spring one where
-- it is inert, so it is kept at a neutral 1 instead of a per-leaf number that only
-- pretends to matter. Layer leaves are the only ones it actually times.
hl.animation({ leaf = "borderangle",      enabled = false }) -- frameless
hl.animation({ leaf = "border",           enabled = false }) -- frameless
hl.animation({ leaf = "global",           enabled = true, speed = 1, spring = "spring_glide" })
hl.animation({ leaf = "windows",          enabled = true, speed = 1, spring = "spring_crisp", style = "popin 60%" })
hl.animation({ leaf = "windowsIn",        enabled = true, speed = 1, spring = "spring_crisp", style = "popin 60%" })
hl.animation({ leaf = "windowsOut",       enabled = true, speed = 1, spring = "spring_crisp", style = "popin 60%" })
-- windowsMove covers every in-between motion: tile rearranges, drag/resize AND the
-- scrolling tape. This is what makes windows glide like Denial's.
hl.animation({ leaf = "windowsMove",      enabled = true, speed = 1, spring = "spring_glide" })
hl.animation({ leaf = "fade",             enabled = true, speed = 1, spring = "spring_crisp" })
-- fadeIn/fadeOut are the open/close pair, `fade` the generic one and fadeSwitch
-- the cross-fade when one surface replaces another in place.
hl.animation({ leaf = "fadeIn",           enabled = true, speed = 1, spring = "spring_crisp" })
hl.animation({ leaf = "fadeOut",          enabled = true, speed = 1, spring = "spring_crisp" })
hl.animation({ leaf = "fadeSwitch",       enabled = true, speed = 1, spring = "spring_crisp" })
hl.animation({ leaf = "layers",           enabled = true, speed = 0.9,  bezier = "menu_decel" })
hl.animation({ leaf = "layersIn",         enabled = true, speed = 0.9,  bezier = "menu_decel", style = "slide" })
hl.animation({ leaf = "layersOut",        enabled = true, speed = 0.65, bezier = "menu_accel" })
hl.animation({ leaf = "fadeLayersIn",     enabled = true, speed = 0.75, bezier = "menu_decel" })
hl.animation({ leaf = "fadeLayersOut",    enabled = true, speed = 0.45, bezier = "menu_accel" })
hl.animation({ leaf = "workspaces",       enabled = true, speed = 1, spring = "spring_glide", style = "slide" })
hl.animation({ leaf = "workspacesIn",     enabled = true, speed = 1, spring = "spring_crisp", style = "slide" })
hl.animation({ leaf = "workspacesOut",    enabled = true, speed = 1, spring = "spring_glide", style = "slide" })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 1, spring = "spring_glide", style = "slidefadevert 15%" })
hl.animation({ leaf = "zoomFactor",       enabled = true, speed = 1, spring = "spring_glide" })

-- =====================================================================
-- Window rules (rules.conf + workspaces.nix)
-- =====================================================================
-- Float-on-top windows get their own open animation: `animation` is a real
-- window rule in 0.56 (the Lua API rejects unknown fields outright, so this is
-- validated, not silently ignored). Dialogs and launchers scale in from a wider
-- source than tiled windows (popin 60%) because they are small and centred — a
-- 60% popin on a 45%-wide dialog reads as a blink.
hl.window_rule({ name = "nm-connection-editor", match = { class = "^(nm-connection-editor)$" }, float = true, size = "45% 45%", center = true, animation = "popin 80%", tag = "nm-connection-editor" })
hl.window_rule({ name = "picture-in-picture", match = { title = m.pip }, float = true, keep_aspect_ratio = true, move = "73% 72%", size = "25% 25%", pin = true, animation = "popin 90%", tag = "pip" })
hl.window_rule({ name = "file-dialog", match = { title = m.file_dialog }, center = true, float = true, animation = "popin 80%", tag = "file-dialog" })
hl.window_rule({ name = "telegram-wrapped", match = { class = m.telegram_wrapped }, center = true, tag = "telegram" })
hl.window_rule({ name = "telegram-org", match = { class = m.telegram_org }, float = true, tag = "telegram" })
hl.window_rule({ name = "utility", match = { class = m.utility }, float = true, animation = "popin 85%", tag = "utility" })

-- Scratchpad rules: float + size + no dim (monitor-relative expressions)
hl.window_rule({ name = "im-scratchpad", match = { class = m.im_scratchpad }, float = true, size = "monitor_w*0.3 monitor_h-60", move = "monitor_w*0.7-8 8", no_dim = true })
hl.window_rule({ name = "music-scratchpad", match = { class = m.music_scratchpad }, float = true, size = "monitor_w*0.7 monitor_h*0.4", move = "monitor_w*0.15 monitor_h*0.3", no_dim = true })
hl.window_rule({ name = "mail-scratchpad", match = { class = m.mail_scratchpad }, float = true, size = "monitor_w*0.5 monitor_h*0.5", center = true, no_dim = true })
hl.window_rule({ name = "mixer-scratchpad", match = { class = m.mixer_scratchpad }, float = true, size = "monitor_w*0.4 monitor_h-60", move = "monitor_w*0.6-8 8", no_dim = true })
hl.window_rule({ name = "torrment-scratchpad", match = { class = m.torrment_scratchpad }, float = true, size = "monitor_w-16 monitor_h*0.4", move = "8 8", no_dim = true })
hl.window_rule({ name = "teardown-scratchpad", match = { class = m.teardown_scratchpad }, float = true, size = "monitor_w-16 monitor_h*0.5", move = "8 8", no_dim = true })
hl.window_rule({ name = "vpn-scratchpad", match = { class = "^(vpn)$" }, float = true, size = "monitor_w*0.5 monitor_h*0.3", center = true, no_dim = true })
hl.window_rule({ name = "rebuild-scratchpad", match = { class = m.rebuild_scratchpad }, float = true, size = "monitor_w-16 monitor_h*0.5", move = "8 8", no_dim = true })

-- Scratchpads are frosted like the media popup: hyprglass replaces Hyprland's
-- window blur pass, so a class keeps blur enabled here (window rules only carry
-- `no_blur`, there is no positive `blur` field to switch it back on) and the
-- translucency the frost needs comes from the `kitty-glass` launcher, see
-- modules/user/nix-maid/hyprland/services.nix. The scratchpad classes therefore
-- must stay out of the `routes` table above and away from `no_blur`, or their
-- glass disappears.

-- Scratchpads get their own entrance. The default `popin 60%` scales a window up
-- out of its own middle, which reads as a pop rather than a summon; the special
-- workspace they live on already slides vertically, so a vertical slide+fade
-- makes the desk arrive with the window. Covers every scratchpad class the config
-- knows about: the kitty terminals plus the app scratchpads (telegram, mail).
for i, pattern in ipairs({
  "^teardown$", "^music$", "^torrment$", "^vpn$", "^mixer$", "^rebuild$",
  m.im_scratchpad, m.mail_scratchpad,
}) do
  hl.window_rule({ name = "anim-scratchpad-" .. i, match = { class = pattern }, animation = "slidefadevert 12%" })
end

-- Wine / Steam
hl.window_rule({ name = "wine-exe", match = { title = ".*\\.exe" }, immediate = true, tag = "wine-exe" })
hl.window_rule({ name = "steam-app-generic", match = { class = m.steam_app }, immediate = true, no_shadow = true, tag = "steam-app" })
for _, app in ipairs({
  "1659040", -- hitman 3
  "1144200", -- ready or not
  "730",     -- cs2
  "570",     -- dota 2
  "1172470", -- apex
  "2357570", -- overwatch 2
  "440",     -- tf2
  "2073850", -- the finals
  "240",     -- css
  "550",     -- l4d2
  "1237970", -- titanfall 2
}) do
  hl.window_rule({ name = "steam-" .. app, match = { class = "^(steam_app_" .. app .. ")$" }, immediate = true })
end
hl.window_rule({ name = "soulstone-survivors", match = { class = "^(steam_app_2066020)$" }, render_unfocused = true, no_blur = true })
hl.window_rule({ name = "gaming-immediate", match = { class = "^(osu!|cs2)$" }, immediate = true })
-- Exclude kitty from hyprglass glass shader
hl.window_rule({ name = "hgrm-term", match = { class = "^(kitty|term)$" }, tag = "+hyprglass_disabled" })
-- Glass over video and over fullscreen surfaces only costs GPU time
hl.window_rule({ name = "hgrm-mpv", match = { class = "^(mpv)$" }, tag = "+hyprglass_disabled" })
hl.window_rule({ name = "hgrm-fullscreen", match = { fullscreen = true }, tag = "+hyprglass_disabled" })

-- Stretch only the dedicated term workspace window to fill the monitor
-- (kitty launched as class=term; plain kitty keeps its own size)
hl.window_rule({ name = "term-fill", match = { class = "^(term)$" }, size = "100% 100%" })

-- Fullscreen video/gpu-heavy apps: force immediate rendering for direct scanout
hl.window_rule({ name = "video-immediate", match = { class = "^(mpv)$" }, immediate = true })
hl.window_rule({ name = "gamescope-immediate", match = { class = "^(gamescope)$" }, immediate = true })

-- Float all windows on the games workspace (id 4) — games don't tile well
hl.window_rule({ name = "games-float", match = { workspace = "4" }, float = true })

-- Floats / misc
hl.window_rule({ name = "bitwarden", match = { title = "^(.*Bitwarden Password Manager.*)$" }, float = true })
hl.window_rule({ name = "calculator", match = { class = "^(org.gnome.Calculator)$" }, float = true, size = "360 490" })
hl.window_rule({ name = "browser-pip", match = { title = "^(Picture-in-Picture)$" }, float = true, pin = true })

-- xwayland / focus hygiene
hl.window_rule({ name = "suppress-maximize", match = { class = ".*" }, suppress_event = "maximize" })
hl.window_rule({ name = "fix-xwayland-drags", match = { class = "^$", title = "^$", xwayland = true, float = true, fullscreen = false, pin = false }, no_focus = true })
hl.window_rule({ name = "no-blur-xwayland", match = { xwayland = true }, no_blur = true })
hl.window_rule({ name = "tag-xwayland", match = { xwayland = true }, tag = "xwayland" })
hl.window_rule({ name = "pinentry", match = { class = "(pinentry-)(.*)" }, stay_focused = true, tag = "pinentry" })
hl.window_rule({ name = "file-manager", match = { class = m.file_manager }, opacity = 0.92, tag = "file-manager" })
hl.window_rule({ name = "xwayland-video-bridge", match = { class = m.xwaylandvideobridge }, opacity = 0.0, no_anim = true, no_initial_focus = true, max_size = "1 1", no_blur = true, tag = "xwaylandvideobridge" })

-- swayimg (workspaces.nix). Pseudo-fullscreen: maximize (internal state 1) fills
-- the monitor work area and keeps the bar on top, unlike the client's real
-- fullscreen request (swayimg's -F / toggle_fullscreen are disabled). Un-maximizing
-- falls back to the floating geometry from the rule above.
hl.window_rule({ name = "swayimg", match = { class = cls.pic }, float = true, size = "1200 800", move = "100 100", tag = "swayimg" })
hl.window_rule({ name = "pic-pseudo-fullscreen", match = { class = cls.pic }, maximize = true })

-- No borders / rounding on TV / fullscreen workspaces
hl.window_rule({ name = "no-border-tv", match = { workspace = "w[tv1]" }, border_size = 0, rounding = 0 })
hl.window_rule({ name = "no-border-f1", match = { workspace = "f[1]" }, border_size = 0, rounding = 0 })

-- =====================================================================
-- Workspace routing (classes.conf + workspaces.conf / workspaces.nix)
-- Each class is auto-routed to its workspace with blur disabled.
-- =====================================================================
local routes = {
  { class = cls.term,        id = 1,  no_blur = true },
  { class = cls.web,         id = 2 },
  { class = cls.dev,         id = 3 },
  { class = cls.games,       id = 4 },
  { class = cls.doc,         id = 5 },
  { class = cls.vid,         id = 6 },
  { class = cls.obs,         id = 7 },
  { class = cls.pic,         id = 8 },
  { class = cls.vm,          id = 9 },
  { class = cls.wine,        id = 10 },
  { class = cls.daw,         id = 12 },
  { class = cls.dw,          id = 13 },
  { class = cls.keyboard,    id = 14 },
  { class = cls.im,          id = 15 },
  { class = cls.remote,      id = 16 },
  { class = cls.notes,       id = 17 },
  { class = cls.vital,       id = 18 },
}

for _, r in ipairs(routes) do
  local rule = { name = "route-" .. r.id, match = { class = r.class }, no_blur = true, workspace = tostring(r.id) }
  if r.float then rule.float = true end
  hl.window_rule(rule)
end

-- VCV Rack: WM_CLASS is the shared "GLFW-Application", so route by the
-- stable title prefix "VCV Rack" (a class route would catch every GLFW app).
hl.window_rule({ name = "route-rack", match = { title = "^VCV Rack" }, no_blur = true, workspace = "19" })

-- =====================================================================
-- Layer rules (rules.conf)
-- =====================================================================
-- xray: see through all layers
hl.layer_rule({ name = "xray-all", match = { namespace = ".*" }, xray = true })

-- no animation
for _, ns in ipairs({ "selection", "indicator.*", "hyprpicker" }) do
  hl.layer_rule({ name = "noanim-" .. ns, match = { namespace = ns }, no_anim = true })
end

-- blur with per-namespace ignore_alpha
local blur_layers = {
  { ns = "qs-.*",           ia = 0.05 }, -- was 0.6: the bar chips are semi-transparent, 0.6 dropped their blur
  { ns = "quickshell",      ia = 0.5 },
  { ns = "vicinae",         ia = 0.6 },
  { ns = "launcher",        ia = 0.5 },
  { ns = "notifications",   ia = 0.69 },
  { ns = "shell:notifications", ia = 0.5 },
  { ns = "shell:notification-center", ia = 0.5 },
  { ns = "session[0-9]*" },
  { ns = "bar[0-9]*",       ia = 0.6 },
  { ns = "barcorner.*",     ia = 0.6 },
  { ns = "dock[0-9]*",      ia = 0.6 },
  { ns = "overview[0-9]*",  ia = 0.6 },
  { ns = "cheatsheet[0-9]*", ia = 0.6 },
  { ns = "sideright[0-9]*", ia = 0.6 },
  { ns = "sideleft[0-9]*",  ia = 0.6 },
  { ns = "indicator.*",     ia = 0.6 },
  { ns = "osk[0-9]*",       ia = 0.6 },
}
for _, l in ipairs(blur_layers) do
  local rule = { name = "blur-" .. l.ns, match = { namespace = l.ns }, blur = true }
  if l.ia ~= nil then rule.ignore_alpha = l.ia end
  hl.layer_rule(rule)
end

-- slide animations for side panels
hl.layer_rule({ name = "slide-left", match = { namespace = "sideleft.*" }, animation = "slide left" })
hl.layer_rule({ name = "slide-right", match = { namespace = "sideright.*" }, animation = "slide right" })

-- quickshell's notification toasts and its history sidebar are bottom-right /
-- right-edge surfaces (namespaces "shell:*", not the older "notifications"
-- ones the blur pass still lists), so they enter from the right edge instead of
-- only cross-fading.
hl.layer_rule({ name = "slide-notif", match = { namespace = "shell:notifications" }, animation = "slide right" })
hl.layer_rule({ name = "slide-notif-center", match = { namespace = "shell:notification-center" }, animation = "slide right" })

-- bottom-up slide for overlay popups
hl.layer_rule({ name = "slide-up", match = { namespace = "qs-weather" }, animation = "slide bottom" })
hl.layer_rule({ name = "slide-up-cal", match = { namespace = "qs-calendar" }, animation = "slide bottom" })
hl.layer_rule({ name = "slide-up-mon", match = { namespace = "qs-monitor" }, animation = "slide bottom" })

-- =====================================================================
-- Autostart (autostart.conf / env.conf) -- NixOS-appropriate
-- =====================================================================
hl.on("hyprland.start", function()
  -- Restart the session target chain: import env, clean stale portals and
  -- stop/start hyprland-session.target so quickshell, hypridle, hyprscratch
  -- and ru-layout come back after a Hyprland (re)start.
  hl.exec_cmd("hypr-start")

  -- Liquid glass: loads the plugin and pushes files/gui/hypr/hyprglass.lua
  hl.exec_cmd("@hyprglass_setup@")

  -- HyprExpo: same load-then-push pattern (plugin .so + files/gui/hypr/hyprexpo.lua).
  -- Re-runnable in a live session: `hyprexpo-setup` (also in PATH).
  hl.exec_cmd("@hyprexpo_setup@")

  -- HyprWindowShade: per-window/per-layer fragment shaders. Same load-then-push
  -- pattern; re-runnable in a live session as `hyprwindowshade-setup`.
  hl.exec_cmd("@hyprwindowshade_setup@")
  hl.exec_cmd("systemctl --user restart quickshell.service")
  hl.exec_cmd("systemctl --user restart hyprscratch.service")
  hl.exec_cmd("systemctl --user start wl-daemon.service")
  hl.exec_cmd("wl-restore")
  hl.exec_cmd("kitty --single-instance --class term")
  hl.exec_cmd("telegram-desktop")
  hl.exec_cmd("vesktop")
  hl.exec_cmd("wl-clip-persist --clipboard regular")
  hl.exec_cmd("zsh -c 'pkill \"wl-paste --watch cliphist store\"; wl-paste --watch cliphist store'")
  hl.exec_cmd("nicotine -s") -- start hidden (Soulseek client); summon via special-submap d
  hl.exec_cmd("wayscriber --daemon") -- keep the annotation overlay resident; M4+SHIFT+Z toggles it
  hl.exec_cmd("systemctl --user start --no-block vicinae.service")
  -- Warm the menu-search entry cache once the tray apps have registered their
  -- StatusNotifierItems: the window is fed from that cache, so Super+Shift+M
  -- opens without walking the bus for every menu (menu-search --refresh; it also
  -- refreshes in the background on every use).
  hl.exec_cmd("zsh -c 'sleep 8; menu-search --refresh'")
  hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE QT_XDG_DESKTOP_PORTAL QT_STYLE_OVERRIDE QT_QPA_PLATFORMTHEME")
  hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE QT_XDG_DESKTOP_PORTAL QT_STYLE_OVERRIDE QT_QPA_PLATFORMTHEME")
end)

-- Ensure the quickshell panel is running after every config reload
-- (systemctl start is a no-op when the service is already active,
-- so this never spawns more than one instance).
hl.on("config.reloaded", function()
  hl.exec_cmd("systemctl --user start quickshell.service")
end)

-- Keep the primary monitor as the home for all workspaces
hl.on("monitor.added", function(monitor_name)
  if monitor_name == "DP-2" then
    hl.exec_cmd("systemctl --user restart hyprscratch.service")
    for _, ws in ipairs(hl.get_workspaces()) do
      if ws.monitor ~= "DP-2" then
        hl.dsp.workspace.move({ workspace = ws.id, monitor = "DP-2" })
      end
    end
  end
end)

hl.on("monitor.removed", function(monitor_name)
  if monitor_name == "DP-2" then
    hl.exec_cmd("notify-send -u low 'Monitor DP-2 disconnected'")
  end
end)
