-- =====================================================================
-- Hyprland configuration (Lua / hyprlang Lua API)
--
-- Migrated from the CachyOS `hyprland.lua` template, merged with the
-- current NixOS conf-based config (init.conf, vars.conf, classes.conf,
-- rules.conf, workspaces.conf, bindings/*, animations/neg.conf and
-- modules/user/nix-maid/hyprland/workspaces.nix).
--
-- Source of truth for behaviour is the NixOS config; the CachyOS file
-- provided the Lua API structure (hl.*).
-- =====================================================================

hl.config({ autogenerated = false })

-- ---------------------------------------------------------------------
-- Visual variables (from vars.conf)
-- ---------------------------------------------------------------------
local border_size            = 1
local col_border_active_base = "rgba(00285981)"
local col_border_inactive    = "rgba(00000000)"
local rounding               = 0
local rounding_power         = 0
local opacity_active         = 1.0
local opacity_inactive       = 1.0
local shadow_color           = 0xaa005faf -- rgba(005fafaa)
local blur_size              = 9
local blur_passes            = 2
local blur_vibrancy          = 0.1696

-- ---------------------------------------------------------------------
-- Common window matcher regexes (from vars.conf / classes.conf)
-- NOTE: in Lua strings "\\." == regex "\." (a literal dot)
-- ---------------------------------------------------------------------
local m = {
  browser            = "^([Vv]ivaldi-stable|[Vv]ivaldi)$",
  file_dialog        = "^(Open File|Select a File|Choose wallpaper|Open Folder|Save As|Library|File Upload)(.*)$",
  pip                = "^([Pp]icture[-\\s]?[Ii]n[-\\s]?[Pp]icture)(.*)$",
  telegram_wrapped   = "^(.telegram-desktop-wrapped)$",
  telegram_org       = "^(org\\.telegram.desktop)$",
  utility            = "^(qt5ct|wine|steamwebhelper|sun-awt-X11-XFramePeer|xdg-desktop-portal-gtk)$",
  mpd_add            = "^(mpd-add)(.*)$",
  steam_app          = "^(steam_app)",
  xwaylandvideobridge = "^(xwaylandvideobridge)$",
  -- scratchpad classes
  im_scratchpad      = "^(KotatogramDesktop|Skype|Slack|TelegramDesktop|org\\.telegram\\.desktop|zoom)$",
  music_scratchpad   = "^(ncmpcpp|rmpc|music)$",
  mail_scratchpad    = "^(mutterfox|neomutt)$",
  mixer_scratchpad   = "^(ncpamixer|com\\.saivert\\.pwvucontrol)$",
  torrment_scratchpad = "^(torrment)$",
  teardown_scratchpad = "^(teardown)$",
}

-- Workspace routing classes (from classes.conf)
local cls = {
  term        = "^(term)$",
  web         = "^([Vv]ivaldi-stable|[Vv]ivaldi)$",
  dev         = "^(nwim)$",
  games       = "^(steam|Steam)$",
  doc         = "^(sioyek)$",
  vid         = "^(mpv)$",
  obs         = "^(obs)$",
  pic         = "^swayimg$",
  vm          = "^(.virt-manager-wrapped|qemu-system-x86_64|Qemu-system-x86_64)$",
  wine        = "^(com.usebottles.bottles)$",
  patchbay    = "^(zestbay|Carla2)$",
  daw         = "^(Renoise)$",
  keyboard    = "^(Bazecor|wootility-lekker|Vial|via)$",
  im          = "^(im.riot.Riot)$",
  remote      = "^(Vmware-view|xfreerdp|remmina|org.remmina.Remmina)$",
  notes       = "^(Obsidian)$",
  winboat     = "^(winboat|WinBoat)$",
}

-- ---------------------------------------------------------------------
-- Monitors (from init.conf)
-- ---------------------------------------------------------------------
hl.monitor({ output = "DP-2", mode = "3840x2160@240", position = "0x0", scale = 2, vrr = 0, bitdepth = 10, cm = "auto" })
hl.monitor({ output = "DP-1", disabled = true })

-- ---------------------------------------------------------------------
-- Environment (from env.conf)
-- ---------------------------------------------------------------------
hl.env("CLUTTER_BACKEND", "wayland")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
hl.env("GDK_BACKEND", "wayland")
hl.env("GDK_SCALE", "2")
hl.env("MOZ_ENABLE_WAYLAND", "1")
hl.env("QML_XHR_ALLOW_FILE_READ", "1")
hl.env("QT_AUTO_SCREEN_SCALE_FACTOR", "1")
hl.env("QT_ENABLE_HIGHDPI_SCALING", "1")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("QT_STYLE_OVERRIDE", "kvantum")
hl.env("QT_XDG_DESKTOP_PORTAL", "1")
hl.env("SDL_VIDEODRIVER", "wayland,x11")
hl.env("XCURSOR_SIZE", "23")
hl.env("XCURSOR_THEME", "Alkano-aio")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")

-- ---------------------------------------------------------------------
-- Core configuration (from init.conf) -- master layout
-- ---------------------------------------------------------------------
hl.config({
  general = {
    gaps_in = 0, gaps_out = 0, border_size = border_size,
    col = {
      active_border = { colors = { col_border_active_base, col_border_active_base }, angle = 45 },
      inactive_border = col_border_inactive,
    },
    resize_on_border = false, allow_tearing = true, layout = "master",
  },
  decoration = {
    rounding = rounding, rounding_power = rounding_power,
    active_opacity = opacity_active, inactive_opacity = opacity_inactive,
    shadow = { enabled = false, range = 4, render_power = 1, color = shadow_color },
    blur = { enabled = true, size = blur_size, passes = blur_passes, vibrancy = blur_vibrancy },
    dim_special = false,
  },
  input = {
    kb_layout = "us,ru", kb_variant = "", kb_model = "", kb_options = "", kb_rules = "",
    follow_mouse = 1, sensitivity = 0, repeat_rate = 35, repeat_delay = 250,
    touchpad = { natural_scroll = true, disable_while_typing = true, clickfinger_behavior = true },
  },
  misc = {
    disable_hyprland_logo = false, enable_anr_dialog = false, force_default_wallpaper = 0,
    font_family = "Iosevka", splash_font_family = "Iosevka",
    vrr = 3, enable_swallow = true, middle_click_paste = false, disable_autoreload = 1,
  },
  cursor = {
    sync_gsettings_theme = true, min_refresh_rate = 240, inactive_timeout = 3.0,
    hide_on_key_press = true, warp_on_change_workspace = false,
  },
  render = { direct_scanout = 2 },
  xwayland = { force_zero_scaling = true, use_nearest_neighbor = true },
  master = { new_status = "master", mfact = 0.6, orientation = "left", allow_small_split = true, smart_resizing = true },
})

-- Screencopy and permissions now handled natively by Hyprland Lua API

-- =====================================================================
-- Keybindings (from bindings.conf and bindings/*)
-- =====================================================================
local M4 = "SUPER"
local M1 = "ALT"
local C  = "CTRL"
local SH = "SHIFT"

local browser = "vivaldi"
local menu    = "vicinae toggle"

-- Raw dispatch helper for dispatchers without a dedicated hl.dsp.* helper
local function dispatch(args) return hl.dsp.exec_cmd("hyprctl dispatch " .. args) end

-- --- Top-level binds (bindings.conf) ---
hl.bind(M4 .. "+S", hl.dsp.exec_cmd("hyprctl switchxkblayout current next"))
hl.bind(M1 .. "+Tab", hl.dsp.focus({ workspace = "previous" }))
hl.bind(M4 .. "+slash", hl.dsp.focus({ workspace = "previous" }))
hl.bind(M4 .. "+" .. C .. "+backslash", hl.dsp.window.resize({ x = 640, y = 480 }))
hl.bind(M4 .. "+Tab", hl.dsp.window.cycle_next({ next = true }))
hl.bind(M4 .. "+c", hl.dsp.exec_cmd("vicinae deeplink vicinae://launch/clipboard/history"))
hl.bind(M4 .. "+Escape", hl.dsp.window.close())
hl.bind(M4 .. "+r", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind(M4 .. "+h", hl.dsp.exec_cmd("hyprctl dispatch movefocus l"))
hl.bind(M4 .. "+j", hl.dsp.exec_cmd("hyprctl dispatch movefocus d"))
hl.bind(M4 .. "+k", hl.dsp.exec_cmd("hyprctl dispatch movefocus u"))
hl.bind(M4 .. "+l", hl.dsp.exec_cmd("hyprctl dispatch movefocus r"))
hl.bind(M4 .. "+Return", hl.dsp.exec_cmd("kitty"), { locked = true })
hl.bind(M4 .. "+p", hl.dsp.exec_cmd("pass-2col"), { locked = true })
hl.bind(M4 .. "+mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(M4 .. "+mouse_up", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(M4 .. "+mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(M4 .. "+mouse:273", hl.dsp.window.resize(), { mouse = true })

-- --- Scratchpads (sashetophizika/hyprscratch with special workspace) ---
hl.bind(M4 .. "+d", hl.dsp.exec_cmd("hyprscratch teardown 'kitty --class teardown -e btop' special"))
hl.bind(M4 .. "+e", hl.dsp.exec_cmd("hyprscratch toggle telegram"))
hl.bind(M4 .. "+f", hl.dsp.exec_cmd("hyprscratch music 'kitty --class music -e rmpc' special"))
hl.bind(M4 .. "+t", hl.dsp.exec_cmd("hyprscratch torrment 'kitty --class torrment -e rustmission' special"))
hl.bind(M4 .. "+u", hl.dsp.exec_cmd("hyprscratch vpn 'kitty --class vpn -e sing-box tun' special"))
hl.bind(M4 .. "+" .. C .. "+p", hl.dsp.exec_cmd("hyprscratch mixer 'kitty --class mixer -e ncpamixer' special"))
hl.bind(M4 .. "+" .. SH .. "+h", hl.dsp.exec_cmd("hyprscratch hide-all"))

-- --- App launchers (apps.conf) ---
hl.bind(M4 .. "+w", hl.dsp.exec_cmd('raise --match "class:regex=' .. m.browser .. '" --launch ' .. browser))
hl.bind(M4 .. "+x", hl.dsp.exec_cmd('raise --match "class:regex=^term$" --launch "kitty --class term"'))
hl.bind(M4 .. "+q", hl.dsp.exec_cmd('raise --match "class:regex=^nwim$" --launch "kitty --class nwim -e /home/neg/.local/bin/v"'))
hl.bind(M4 .. "+b", hl.dsp.exec_cmd('raise --match "class:regex=^mpv$" --launch "~/.local/bin/pl video"'))
hl.bind(M4 .. "+" .. C .. "+c", hl.dsp.exec_cmd('raise --match "class:regex=^swayimg$" --launch "swayimg ~/dw"'))
hl.bind(M4 .. "+" .. SH .. "+c", hl.dsp.exec_cmd("wl random ~/pic/wl ~/pic/black"))
hl.bind(M4 .. "+" .. C .. "+v", hl.dsp.exec_cmd('raise --match "class:regex=^Bazecor$" --launch "bazecor"'))
hl.bind(M4 .. "+g", hl.dsp.exec_cmd('raise --match "class:regex=^(steam|com\\.valvesoftware\\.Steam|steam_app.*|gamescope)$" --launch "steam"'))
hl.bind(M4 .. "+" .. C .. "+o", hl.dsp.exec_cmd('raise --match "class:regex=^(obs|com\\.obsproject\\.Studio)$" --launch "obs"'))
hl.bind(M4 .. "+" .. C .. "+n", hl.dsp.exec_cmd('raise --match "class:regex=^(Obsidian|md\\.obsidian\\.Obsidian)$" --launch "obsidian"'))

-- --- Media (media.conf) ---
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("swayosd-client --output-volume +5"), { repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("swayosd-client --output-volume -5"), { repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("swayosd-client --output-volume mute-toggle"), { repeating = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("swayosd-client --input-volume mute-toggle"), { repeating = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("swayosd-client --brightness +10"), { repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("swayosd-client --brightness -10"), { repeating = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })
hl.bind(M4 .. "+" .. SH .. "+w", hl.dsp.exec_cmd("~/.local/bin/pl cmd play-pause"), { locked = true })
hl.bind(M4 .. "+comma", hl.dsp.exec_cmd("~/.local/bin/pl cmd previous"), { locked = true })
hl.bind(M4 .. "+period", hl.dsp.exec_cmd("~/.local/bin/pl cmd next"), { locked = true })
hl.bind(M4 .. "+" .. SH .. "+i", hl.dsp.exec_cmd("~/.local/bin/pl vol mute"), { locked = true })
hl.bind(M4 .. "+" .. SH .. "+o", hl.dsp.exec_cmd("~/.local/bin/pl vol unmute"), { locked = true })
hl.bind(M4 .. "+m", hl.dsp.exec_cmd("~/.local/bin/music-rename current"), { locked = true })

-- --- Misc (misc.conf) ---
hl.bind(M1 .. "+g", hl.dsp.exec_cmd("vicinae deeplink vicinae://launch/wm/switch-windows"))
hl.bind(M4 .. "+" .. SH .. "+m", hl.dsp.exec_cmd("~/.local/bin/main-menu"))
hl.bind(M4 .. "+" .. SH .. "+p", hl.dsp.exec_cmd("~/.local/bin/hypr-shortcuts"))
hl.bind(M4 .. "+" .. SH .. "+r", hl.dsp.exec_cmd('shot="$HOME/pic/shots/satty-$(date \'+%Y%m%d-%H.%M.%S\').png"; grimblast save screen "$shot" && pic-info "$shot"'))
hl.bind(M4 .. "+" .. SH .. "+" .. C .. "+r", hl.dsp.exec_cmd('shot="$HOME/pic/shots/satty-$(date \'+%Y%m%d-%H.%M.%S\').png"; grimblast save area "$shot" && pic-info "$shot"'))
hl.bind(M4 .. "+" .. SH .. "+v", hl.dsp.exec_cmd("~/.local/bin/screenrec screen"))
hl.bind(M4 .. "+" .. SH .. "+" .. C .. "+v", hl.dsp.exec_cmd("~/.local/bin/screenrec area"))
hl.bind(M1 .. "+q", hl.dsp.exec_cmd(menu))
hl.bind("Caps_Lock", hl.dsp.exec_cmd("swayosd-client --caps-lock"))
hl.bind(M4 .. "+apostrophe", hl.dsp.exec_cmd("hypr-fix"))

-- --- Notifications (notify.conf) ---
hl.bind(M4 .. "+n", hl.dsp.exec_cmd("dunstctl history-pop"))
hl.bind(M4 .. "+space", hl.dsp.exec_cmd("dunstctl close-all"), { locked = true })

-- --- Split ratio helpers (tiling-helpers.conf) ---
hl.bind(M4 .. "+" .. C .. "+d", dispatch("splitratio -0.1"), { repeating = true })
hl.bind(M4 .. "+" .. C .. "+f", dispatch("splitratio +0.1"), { repeating = true })

-- =====================================================================
-- Submaps (bindings/_resets.conf and submap files)
-- =====================================================================
local function submap_resets()
  hl.bind("escape", hl.dsp.submap("reset"))
  hl.bind(C .. "+c", hl.dsp.submap("reset"))
  hl.bind(C .. "+q", hl.dsp.submap("reset"))
  hl.bind("q", hl.dsp.submap("reset"))
end

local function bind_reset(key, fn)
  hl.bind(key, fn)
  hl.bind(key, hl.dsp.submap("reset"))
end

local function binde_reset(key, fn)
  hl.bind(key, fn, { repeating = true })
  hl.bind(key, hl.dsp.submap("reset"), { repeating = true })
end

-- Submap: resize (resize.conf)
hl.bind(M4 .. "+" .. M1 .. "+r", hl.dsp.submap("resize"))
hl.define_submap("resize", "reset", function()
  submap_resets()
  hl.bind("right", hl.dsp.window.resize({ x = 10, y = 0, relative = true }), { repeating = true })
  hl.bind("left",  hl.dsp.window.resize({ x = -10, y = 0, relative = true }), { repeating = true })
  hl.bind("up",    hl.dsp.window.resize({ x = 0, y = -10, relative = true }), { repeating = true })
  hl.bind("down",  hl.dsp.window.resize({ x = 0, y = 10, relative = true }), { repeating = true })
  hl.bind("l", hl.dsp.window.resize({ x = 10, y = 0, relative = true }), { repeating = true })
  hl.bind("h", hl.dsp.window.resize({ x = -10, y = 0, relative = true }), { repeating = true })
  hl.bind("k", hl.dsp.window.resize({ x = 0, y = -10, relative = true }), { repeating = true })
  hl.bind("j", hl.dsp.window.resize({ x = 0, y = 10, relative = true }), { repeating = true })
  hl.bind(SH .. "+l", hl.dsp.window.resize({ x = -10, y = 0, relative = true }), { repeating = true })
  hl.bind(SH .. "+h", hl.dsp.window.resize({ x = 10, y = 0, relative = true }), { repeating = true })
  hl.bind(SH .. "+k", hl.dsp.window.resize({ x = 0, y = 10, relative = true }), { repeating = true })
  hl.bind(SH .. "+j", hl.dsp.window.resize({ x = 0, y = -10, relative = true }), { repeating = true })
  hl.bind("Return", hl.dsp.submap("reset"))
end)

-- Submap: special (special.conf)
hl.bind(M1 .. "+e", hl.dsp.submap("special"))
hl.define_submap("special", "reset", function()
  submap_resets()
  binde_reset("q", hl.dsp.exec_cmd('raise --match "class:regex=^zestbay$" --launch "zestbay"'))
  binde_reset(SH .. "+q", hl.dsp.exec_cmd('raise --match "class:regex=^Carla2$" --launch "carla"'))
  binde_reset(SH .. "+l", hl.dsp.exec_cmd("hyprctl switchxkblayout current 0 && hyprlock"))
  binde_reset("e", hl.dsp.window.float({ action = "toggle" }))
  binde_reset("f", hl.dsp.window.fullscreen_state({ internal = 0, client = 3, action = "toggle" }))
  binde_reset("z", hl.dsp.window.fullscreen_state({ internal = 0, client = 3, action = "toggle" }))
  hl.bind("semicolon", hl.dsp.submap("reset"), { repeating = true })
  binde_reset(SH .. "+w", hl.dsp.exec_cmd("pkill iwmenu || iwmenu"))
  binde_reset("o", hl.dsp.exec_cmd('raise --match "title:regex=' .. m.file_dialog .. '"'))
end)

-- Submap: selectors (selectors.conf)
hl.bind(M4 .. "+" .. M1 .. "+S", hl.dsp.submap("selectors"))
hl.define_submap("selectors", "reset", function()
  submap_resets()
  bind_reset("w", hl.dsp.exec_cmd("hyde-selector wallpaper"))
  bind_reset("t", hl.dsp.exec_cmd("hyde-selector theme"))
  bind_reset("a", hl.dsp.exec_cmd("hyde-selector animation"))

  hl.bind("Return", hl.dsp.submap("reset"))
  hl.bind("escape", hl.dsp.submap("reset"))
end)

-- Submap: wallpaper (wallpaper.conf)
hl.bind(M4 .. "+" .. SH .. "+y", hl.dsp.submap("wallpaper"))
hl.define_submap("wallpaper", "reset", function()
  submap_resets()
  hl.bind("y", hl.dsp.exec_cmd("wl random ~/pic/wl ~/pic/black"))
  hl.bind(M4 .. "+y", hl.dsp.exec_cmd("wl random ~/pic/wl ~/pic/black"))
  hl.bind(SH .. "+w", hl.dsp.submap("reset"))
end)

-- Submap: tiling (tiling.conf)
hl.bind(M4 .. "+minus", hl.dsp.submap("tiling"))
hl.define_submap("tiling", "reset", function()
  submap_resets()
  hl.bind(SH .. "+h", hl.dsp.window.move({ direction = "l" }))
  hl.bind(SH .. "+j", hl.dsp.window.move({ direction = "d" }))
  hl.bind(SH .. "+k", hl.dsp.window.move({ direction = "u" }))
  hl.bind(SH .. "+l", hl.dsp.window.move({ direction = "r" }))
end)

-- =====================================================================
-- Workspaces (workspaces.conf / workspaces.nix)
-- =====================================================================
local workspaces = {
  { id = 1,  name = "𐌰:term",   layout = "scrolling" },
  { id = 2,  name = "𐌱:web",    layout = "scrolling" },
  { id = 3,  name = "𐌲:dev",    layout = "scrolling" },
  { id = 4,  name = "𐌸:games" }, -- master (gaming)
  { id = 5,  name = "𐌳:doc",    layout = "scrolling" },
  { id = 6,  name = "𐌴:draw",   layout = "scrolling" },
  { id = 7,  name = "𐌵:vid" },  -- master (media)
  { id = 8,  name = "𐌶:obs" },  -- master (media)
  { id = 9,  name = "𐌷:pic",    layout = "scrolling" },
  { id = 10, name = "𐌹:sys",    layout = "scrolling" },
  { id = 11, name = "𐌺:vm",     layout = "scrolling" },
  { id = 12, name = "𐌻:wine" }, -- master (wine/games)
  { id = 13, name = "𐌼:patchbay", layout = "scrolling" },
  { id = 14, name = "𐌽:daw" },  -- master (media/audio)
  { id = 15, name = "𐌾:dw",     layout = "scrolling" },
  { id = 16, name = "𐌿:keyboard", layout = "scrolling" },
  { id = 17, name = "𐍀:im",     layout = "scrolling" },
  { id = 18, name = "𐍁:remote", layout = "scrolling" },
  { id = 19, name = "Ⲣ:notes",   layout = "scrolling" },
  { id = 20, name = "𐍅:winboat", layout = "scrolling" },
}

for _, w in ipairs(workspaces) do
  local rule = { workspace = tostring(w.id), default_name = w.name }
  if w.layout then rule.layout = w.layout end
  hl.workspace_rule(rule)
end

-- Special on-screen workspaces (TV / fullscreen game), no gaps
hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
hl.workspace_rule({ workspace = "f[1]", gaps_out = 0, gaps_in = 0 })

-- =====================================================================
-- Animations (animations/neg.conf)
-- =====================================================================
hl.curve("myBezier",      { type = "bezier", points = { {0.05, 0.9}, {0.1, 1.05} } })
hl.curve("linear",        { type = "bezier", points = { {0, 0}, {1, 1} } })
hl.curve("md3_standard",  { type = "bezier", points = { {0.2, 0}, {0, 1} } })
hl.curve("md3_decel",     { type = "bezier", points = { {0.05, 0.7}, {0.1, 1} } })
hl.curve("md3_accel",     { type = "bezier", points = { {0.3, 0}, {0.8, 0.15} } })
hl.curve("overshot",      { type = "bezier", points = { {0.05, 0.9}, {0.1, 1.1} } })
hl.curve("crazyshot",     { type = "bezier", points = { {0.1, 1.5}, {0.76, 0.92} } })
hl.curve("hyprnostretch", { type = "bezier", points = { {0.05, 0.9}, {0.1, 1.0} } })
hl.curve("menu_decel",    { type = "bezier", points = { {0.1, 1}, {0, 1} } })
hl.curve("menu_accel",    { type = "bezier", points = { {0.38, 0.04}, {1, 0.07} } })
hl.curve("easeInOutCirc", { type = "bezier", points = { {0.85, 0}, {0.15, 1} } })
hl.curve("easeOutCirc",   { type = "bezier", points = { {0, 0.55}, {0.45, 1} } })
hl.curve("easeOutExpo",   { type = "bezier", points = { {0.16, 1}, {0.3, 1} } })
hl.curve("md2",           { type = "bezier", points = { {0.4, 0}, {0.2, 1} } })

hl.animation({ leaf = "borderangle",      enabled = true, speed = 8,      bezier = "default" })
hl.animation({ leaf = "windows",          enabled = true, speed = 0.1875, bezier = "md3_decel",  style = "popin 60%" })
hl.animation({ leaf = "windowsIn",        enabled = true, speed = 0.1875, bezier = "md3_decel",  style = "popin 60%" })
hl.animation({ leaf = "windowsOut",       enabled = true, speed = 0.1875, bezier = "md3_accel",  style = "popin 60%" })
hl.animation({ leaf = "border",           enabled = true, speed = 0.625,  bezier = "default" })
hl.animation({ leaf = "fade",             enabled = true, speed = 0.1875, bezier = "md3_decel" })
hl.animation({ leaf = "layersIn",         enabled = true, speed = 0.35,   bezier = "menu_decel", style = "slide" })
hl.animation({ leaf = "layersOut",        enabled = true, speed = 0.125,  bezier = "menu_accel" })
hl.animation({ leaf = "fadeLayersIn",     enabled = true, speed = 0.125,  bezier = "menu_decel" })
hl.animation({ leaf = "fadeLayersOut",    enabled = true, speed = 0.03125, bezier = "menu_accel" })
hl.animation({ leaf = "workspaces",       enabled = true, speed = 0.125,  bezier = "menu_decel", style = "slide" })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 0.1875, bezier = "md3_decel",  style = "slidefadevert 15%" })

-- =====================================================================
-- Window rules (rules.conf + workspaces.nix)
-- =====================================================================
hl.window_rule({ name = "nm-connection-editor", match = { class = "^(nm-connection-editor)$" }, float = true, size = "45% 45%", center = true, tag = "nm-connection-editor" })
hl.window_rule({ name = "picture-in-picture", match = { title = m.pip }, float = true, keep_aspect_ratio = true, move = "73% 72%", size = "25% 25%", pin = true, tag = "pip" })
hl.window_rule({ name = "file-dialog", match = { title = m.file_dialog }, center = true, float = true, tag = "file-dialog" })
hl.window_rule({ name = "telegram-wrapped", match = { class = m.telegram_wrapped }, center = true, tag = "telegram" })
hl.window_rule({ name = "telegram-org", match = { class = m.telegram_org }, float = true, tag = "telegram" })
hl.window_rule({ name = "utility", match = { class = m.utility }, float = true, tag = "utility" })
hl.window_rule({ name = "mpd-add", match = { class = m.mpd_add }, float = true, size = "35% 35%", move = "64% 59%", tag = "mpd-add" })

-- Scratchpad rules: float + size + no dim (monitor-relative expressions)
hl.window_rule({ name = "im-scratchpad", match = { class = m.im_scratchpad }, float = true, size = "monitor_w*0.3 monitor_h-60", move = "monitor_w*0.7 - 8 8", no_dim = true })
hl.window_rule({ name = "music-scratchpad", match = { class = m.music_scratchpad }, float = true, size = "monitor_w*0.7 monitor_h*0.4", move = "monitor_w*0.15 monitor_h*0.3", no_dim = true })
hl.window_rule({ name = "mail-scratchpad", match = { class = m.mail_scratchpad }, float = true, size = "monitor_w*0.5 monitor_h*0.5", center = true, no_dim = true })
hl.window_rule({ name = "mixer-scratchpad", match = { class = m.mixer_scratchpad }, float = true, size = "monitor_w*0.4 monitor_h-60", move = "monitor_w*0.6 - 8 8", no_dim = true })
hl.window_rule({ name = "torrment-scratchpad", match = { class = m.torrment_scratchpad }, float = true, size = "monitor_w-16 monitor_h*0.4", move = "8 8", no_dim = true })
hl.window_rule({ name = "teardown-scratchpad", match = { class = m.teardown_scratchpad }, float = true, size = "monitor_w-16 monitor_h*0.5", move = "8 8", no_dim = true })
hl.window_rule({ name = "vpn-scratchpad", match = { class = "^(vpn)$" }, float = true, size = "monitor_w*0.5 monitor_h*0.3", center = true, no_dim = true })

-- Wine / Steam
hl.window_rule({ name = "wine-exe", match = { title = ".*\\.exe" }, immediate = true, tag = "wine-exe" })
hl.window_rule({ name = "steam-app-generic", match = { class = m.steam_app }, immediate = true, no_shadow = true, tag = "steam-app" })
for _, app in ipairs({
  "1659040", -- hitman 3
  "1144200", -- ready or not
  "730",     -- cs2
  "570",     -- dota 2
  "1172470", -- apex
  "2357570", -- overwatch 2
  "440",     -- tf2
  "2073850", -- the finals
  "240",     -- css
  "550",     -- l4d2
  "1237970", -- titanfall 2
}) do
  hl.window_rule({ name = "steam-" .. app, match = { class = "^(steam_app_" .. app .. ")$" }, immediate = true })
end
hl.window_rule({ name = "soulstone-survivors", match = { class = "^(steam_app_2066020)$" }, render_unfocused = true, no_blur = true })
hl.window_rule({ name = "gaming-immediate", match = { class = "^(osu!|cs2)$" }, immediate = true })
-- Exclude kitty from hyprglass glass shader
hl.window_rule({ name = "hgrm-term", match = { class = "^(kitty|term)$" }, tag = "hyprglass_disabled" })

-- Fullscreen video/gpu-heavy apps: force immediate rendering for direct scanout
hl.window_rule({ name = "video-immediate", match = { class = "^(mpv)$" }, immediate = true })
hl.window_rule({ name = "gamescope-immediate", match = { class = "^(gamescope)$" }, immediate = true })

-- Float all windows on the games workspace (id 4) — games don't tile well
hl.window_rule({ name = "games-float", match = { workspace = "4" }, float = true })

-- Floats / misc
hl.window_rule({ name = "bitwarden", match = { title = "^(.*Bitwarden Password Manager.*)$" }, float = true })
hl.window_rule({ name = "calculator", match = { class = "^(org.gnome.Calculator)$" }, float = true, size = "360 490" })
hl.window_rule({ name = "browser-pip", match = { title = "^(Picture-in-Picture)$" }, float = true, pin = true })

-- xwayland / focus hygiene
hl.window_rule({ name = "suppress-maximize", match = { class = ".*" }, suppress_event = "maximize" })
hl.window_rule({ name = "fix-xwayland-drags", match = { class = "^$", title = "^$", xwayland = true, float = true, fullscreen = false, pin = false }, no_focus = true })
hl.window_rule({ name = "no-blur-xwayland", match = { xwayland = true }, no_blur = true })
hl.window_rule({ name = "tag-xwayland", match = { xwayland = true }, tag = "xwayland" })
hl.window_rule({ name = "pinentry", match = { class = "(pinentry-)(.*)" }, stay_focused = true, tag = "pinentry" })
hl.window_rule({ name = "file-manager", match = { class = m.file_manager }, opacity = 0.92, tag = "file-manager" })
hl.window_rule({ name = "xwayland-video-bridge", match = { class = m.xwaylandvideobridge }, opacity = 0.0, no_anim = true, no_initial_focus = true, max_size = "1 1", no_blur = true, tag = "xwaylandvideobridge" })

-- swayimg (workspaces.nix)
hl.window_rule({ name = "swayimg", match = { class = "^(swayimg)$" }, float = true, size = "1200 800", move = "100 100", tag = "swayimg" })
hl.window_rule({ name = "pic-fullscreen", match = { class = cls.pic }, fullscreen = true })

-- No borders / rounding on TV / fullscreen workspaces
hl.window_rule({ name = "no-border-tv", match = { workspace = "w[tv1]" }, border_size = 0, rounding = 0 })
hl.window_rule({ name = "no-border-f1", match = { workspace = "f[1]" }, border_size = 0, rounding = 0 })

-- =====================================================================
-- Workspace routing (classes.conf + workspaces.conf / workspaces.nix)
-- Each class is auto-routed to its workspace with blur disabled.
-- =====================================================================
local routes = {
  { class = cls.term,        id = 1,  no_blur = true },
  { class = cls.web,         id = 2 },
  { class = cls.dev,         id = 3 },
  { class = cls.games,       id = 4 },
  { class = cls.doc,         id = 5 },
  { class = cls.vid,         id = 7 },
  { class = cls.obs,         id = 8 },
  { class = cls.pic,         id = 9 },
  { class = cls.vm,          id = 11 },
  { class = cls.wine,        id = 12 },
  { class = cls.patchbay,    id = 13 },
  { class = cls.daw,         id = 14 },
  { class = cls.dw,          id = 15 },
  { class = cls.keyboard,    id = 16 },
  { class = cls.im,          id = 17 },
  { class = cls.remote,      id = 18 },
  { class = cls.notes,       id = 19 },
  { class = cls.winboat,     id = 20, float = true },
}

for _, r in ipairs(routes) do
  local rule = { name = "route-" .. r.id, match = { class = r.class }, no_blur = true, workspace = tostring(r.id) }
  if r.float then rule.float = true end
  hl.window_rule(rule)
end

-- =====================================================================
-- Layer rules (rules.conf)
-- =====================================================================
-- xray: see through all layers
hl.layer_rule({ name = "xray-all", match = { namespace = ".*" }, xray = true })

-- no animation
for _, ns in ipairs({ "selection", "indicator.*", "hyprpicker" }) do
  hl.layer_rule({ name = "noanim-" .. ns, match = { namespace = ns }, no_anim = true })
end

-- blur with per-namespace ignore_alpha
local blur_layers = {
  { ns = "qs-.*",           ia = 0.6 },
  { ns = "vicinae",         ia = 0.6 },
  { ns = "launcher",        ia = 0.5 },
  { ns = "notifications",   ia = 0.69 },
  { ns = "logout_dialog" },
  { ns = "session[0-9]*" },
  { ns = "bar[0-9]*",       ia = 0.6 },
  { ns = "barcorner.*",     ia = 0.6 },
  { ns = "dock[0-9]*",      ia = 0.6 },
  { ns = "overview[0-9]*",  ia = 0.6 },
  { ns = "cheatsheet[0-9]*", ia = 0.6 },
  { ns = "sideright[0-9]*", ia = 0.6 },
  { ns = "sideleft[0-9]*",  ia = 0.6 },
  { ns = "indicator.*",     ia = 0.6 },
  { ns = "osk[0-9]*",       ia = 0.6 },
}
for _, l in ipairs(blur_layers) do
  local rule = { name = "blur-" .. l.ns, match = { namespace = l.ns }, blur = true }
  if l.ia ~= nil then rule.ignore_alpha = l.ia end
  hl.layer_rule(rule)
end

-- slide animations for side panels
hl.layer_rule({ name = "slide-left", match = { namespace = "sideleft.*" }, animation = "slide left" })
hl.layer_rule({ name = "slide-right", match = { namespace = "sideright.*" }, animation = "slide right" })

-- =====================================================================
-- Autostart (autostart.conf / env.conf) -- NixOS-appropriate
-- =====================================================================
hl.on("hyprland.start", function()
  hl.exec_cmd("hyprctl output DP-2 hdr yes")
  hl.exec_cmd("hyprctl eval 'hl.config({ [\"plugin.hyprglass.enabled\"] = true })'")
  hl.exec_cmd("hyprctl eval 'hl.config({ [\"plugin.hyprglass.manage_window_blur\"] = true })'")
  hl.exec_cmd("hyprctl eval 'hl.config({ [\"plugin.hyprglass.layers.enabled\"] = true })'")
  hl.exec_cmd("hyprctl eval 'hl.config({ [\"plugin.hyprglass.layers.namespaces\"] = \"qs-panel,qs-content-left,qs-content-right,quickshell-bar-reserve,quickshell,notifications,qs-music\" })'")
  hl.exec_cmd("hyprctl eval 'hl.config({ [\"plugin.hyprglass.blur_strength\"] = 3 })'")
  hl.exec_cmd("hyprctl eval 'hl.config({ [\"plugin.hyprglass.blur_iterations\"] = 6 })'")
  hl.exec_cmd("hyprctl eval 'hl.config({ [\"plugin.hyprglass.refraction_strength\"] = 0.5 })'")
  hl.exec_cmd("hyprctl eval 'hl.config({ [\"plugin.hyprglass.chromatic_aberration\"] = 0.3 })'")
  hl.exec_cmd("hyprctl eval 'hl.config({ [\"plugin.hyprglass.fresnel_strength\"] = 0.3 })'")
  hl.exec_cmd("hyprctl eval 'hl.config({ [\"plugin.hyprglass.specular_strength\"] = 0.1 })'")
  hl.exec_cmd("hyprctl eval 'hl.config({ [\"plugin.hyprglass.glass_opacity\"] = 0.5 })'")
  hl.exec_cmd("hyprctl eval 'hl.config({ [\"plugin.hyprglass.edge_thickness\"] = 0.05 })'")
  hl.exec_cmd("hyprctl eval 'hl.config({ [\"plugin.hyprglass.adaptive_dim\"] = 0.5 })'")
  hl.exec_cmd("systemctl --user restart quickshell.service")
  hl.exec_cmd("hyprctl eval 'hl.config({ [\"plugin.hyprglass.lens_distortion\"] = 0.05 })'")
  hl.exec_cmd("systemctl --user restart hyprscratch.service")
  hl.exec_cmd("wl init")
  hl.exec_cmd("kitty --single-instance --class term")
  hl.exec_cmd("telegram-desktop")
  hl.exec_cmd("vesktop")
  hl.exec_cmd("wl-clip-persist --clipboard regular")
  hl.exec_cmd("zsh -c 'pkill \"wl-paste --watch cliphist store\"; wl-paste --watch cliphist store'")
  hl.exec_cmd("systemctl --user start --no-block vicinae.service")
  hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE QT_XDG_DESKTOP_PORTAL QT_STYLE_OVERRIDE QT_QPA_PLATFORMTHEME")
  hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY DISPLAY XDG_CURRENT_DESKTOP HYPRLAND_INSTANCE_SIGNATURE QT_XDG_DESKTOP_PORTAL QT_STYLE_OVERRIDE QT_QPA_PLATFORMTHEME")
end)

-- Keep the primary monitor as the home for all workspaces
hl.on("monitor.added", function(monitor_name)
  if monitor_name == "DP-2" then
    hl.exec_cmd("hyprctl output DP-2 hdr yes")
    hl.exec_cmd("systemctl --user restart hyprscratch.service")
    hl.exec_cmd("zsh -c 'hyprctl workspaces -j | jq -r \".[] | select(.monitor != \\\"DP-2\\\") | .id\" | while read ws; do hyprctl dispatch moveworkspacetomonitor \"$ws\" DP-2; done'")
  end
end)

hl.on("monitor.removed", function(monitor_name)
  if monitor_name == "DP-2" then
    hl.exec_cmd("notify-send -u low 'Monitor DP-2 disconnected'")
  end
end)
