{
  pkgs,
  ...
}:
pkgs.mkShell {
  nativeBuildInputs = [
    pkgs.patchelf # Small utility to modify the dynamic linker and RPATH of E...
    pkgs.elfutils # Set of utilities to handle ELF objects
    pkgs.chrpath # Command line tool to adjust the RPATH or RUNPATH of ELF b...
    pkgs.debugedit # Provides programs and scripts for creating debuginfo and ...
    pkgs.dump_syms # Command-line utility for parsing the debugging informatio...
  ];
}
