context.modules = [
    {   name = libpipewire-module-loopback
        args = {
            capture.props = {
                media.class = Audio/Sink
                audio.position = [ FL FR ]
                node.name = game-stereo
                node.description = "Game Stereo"
                priority.session = 1000
                node.target = "alsa_output.pci-0000_05_00.0.pro-output-0"
            }
            playback.props = {
                node.name = "playback.game-stereo"
                audio.position = [ FL FR ]
                stream.dont-remix = true
                target.object = "alsa_output.pci-0000_05_00.0.pro-output-0"
            }
        }
    }
]
