{
  imports = [
    ./boot.nix
    ./environment.nix
    ./filesystems.nix
    ./swapfile.nix
    ./kernel/params.nix
    ./kernel/sysctl.nix
    ./kernel/sysctl-writeback.nix
    ./kernel/sysctl-mem-extras.nix
    ./kernel/sysctl-net-extras.nix
    ./kernel/patches-amd.nix
    ./profiles/security.nix
    ./profiles/performance.nix
    ./profiles/debug.nix
    ./profiles/work.nix
    ./profiles/vm.nix
    ./profiles/aliases.nix
    ./net
    ./tailscale.nix
    ./oomd.nix
    ./wrappers.nix
    ./zram.nix
    ./pkgs.nix
    ./guix.nix
    ./systemd
    ./users.nix
    ./virt.nix
    ./winapps.nix
    ./preserve-flake.nix
  ];
}
