# Pure assertions over lib/ru-keys.nix — eval-only, no derivations.
# Wired into flake/checks.nix as the "ru-keys" check. Keep this file free of
# config/flake dependencies: it is evaluated on every `nix flake check`.
{
  lib,
}:
let
  ru = import ./ru-keys.nix;

  latinLower = lib.stringToCharacters "qwertyuiopasdfghjklzxcvbnm";
  latinUpper = lib.stringToCharacters "QWERTYUIOPASDFGHJKLZXCVBNM";

  # The langmap neovim ships today (files/nvim/lua/00-settings.lua, generated by
  # langmapper.nvim). mkLangmap must reproduce it byte-for-byte: if the table
  # and the lua ever diverge, this check fails first.
  langmapGolden = "ËЙЦУКЕНГШЩЗХЪФЫВАПРОЛДЖЭЯЧСМИТЬБЮ;~QWERTYUIOP{}ASDFGHJKL:\\\"ZXCVBNM<>,ёйцукенгшщзхъфывапролджэячсмить;`qwertyuiop[]asdfghjkl\\;'zxcvbnm";

  check = ok: msg: { inherit ok msg; };

  checks = [
    (check (builtins.length latinLower == 26) "lowercase latin alphabet must be 26 chars")
    (check (builtins.length latinUpper == 26) "uppercase latin alphabet must be 26 chars")
    (check (builtins.all (
      k: ru.toRu k != null
    ) latinLower) "all 26 lowercase letters need a ru counterpart")
    (check (builtins.all (
      k: ru.toRu k != null
    ) latinUpper) "all 26 uppercase letters need a ru counterpart")
    (check (
      (builtins.length (lib.unique (map ru.toRu latinLower))) == 26
    ) "lowercase ru counterparts must be pairwise distinct")
    (check (
      (builtins.length (lib.unique (map ru.toRu latinUpper))) == 26
    ) "uppercase ru counterparts must be pairwise distinct")
    (check (
      (builtins.length (lib.unique (builtins.attrValues ru.latinToRu)))
      == (builtins.length (builtins.attrValues ru.latinToRu))
    ) "lowercase table values must be pairwise distinct")
    (check (
      ru.toRu "1" == null
    ) "digits must have no ru counterpart (they are dropped or kept literal)")
    (check (ru.toRu "г" == null) "cyrillic input must not map anywhere (table is latin→ru only)")

    # Punctuation that moves in ЙЦУКЕН.
    (check (
      ru.latinToRu."," == "б"
      && ru.latinToRu."." == "ю"
      && ru.latinToRu."/" == "."
      && ru.latinToRu."`" == "ё"
    ) "punctuation table")
    (check (
      ru.latinToRu."[" == "х"
      && ru.latinToRu."]" == "ъ"
      && ru.latinToRu.";" == "ж"
      && ru.latinToRu."'" == "э"
    ) "bracket/semicolon table")

    # mkRuKeys: per-char mapping, non-letter keys dropped.
    (check (ru.mkRuKeys [ "j" ] == [ "о" ]) "mkRuKeys single letter")
    (check (
      ru.mkRuKeys [
        "g"
        "g"
      ] == [
        "п"
        "п"
      ]
    ) "mkRuKeys sequence")
    (check (
      ru.mkRuKeys [
        "H"
        "L"
      ] == [
        "Р"
        "Д"
      ]
    ) "mkRuKeys uppercase")
    (check (
      ru.mkRuKeys [
        "j"
        "1"
      ] == [ "о" ]
    ) "mkRuKeys drops keys without counterpart")

    # kittySeq: LITERAL Cyrillic chars (kitty matches by char — keysym names
    # need libxkbcommon which isn't loadable on this system), digits literal,
    # sequences joined with >.
    (check (ru.kittySeq [ "v" ] == "м") "kittySeq letter")
    (check (
      ru.kittySeq [
        "s"
        "f"
      ] == "ы>а"
    ) "kittySeq sequence")
    (check (
      ru.kittySeq [
        "a"
        "1"
      ] == "ф>1"
    ) "kittySeq digit stays literal")
    (check (
      ru.kittySeq [ "[" ] == "х" && ru.kittySeq [ "," ] == "б" && ru.kittySeq [ "`" ] == "ё"
    ) "kittySeq punctuation")

    # mkKittyLines: exact line shape used in files/kitty/key.conf.
    (check (
      ru.mkKittyLines [
        {
          mod = "ctrl+shift";
          keys = [ "v" ];
          action = "paste_from_clipboard";
        }
      ] == [ "map ctrl+shift+м paste_from_clipboard  # v→м" ]
    ) "mkKittyLines single-key line")
    (check (
      ru.mkKittyLines [
        {
          mod = "ctrl+shift";
          keys = [
            "s"
            "f"
          ];
          action = "neghints --program @";
        }
      ] == [ "map ctrl+shift+ы>а neghints --program @  # s→ы, f→а" ]
    ) "mkKittyLines sequence line")

    # mkLangmap: byte-identical to the neovim langmapper.nvim output.
    (check (ru.mkLangmap == langmapGolden) "mkLangmap must match neovim langmapper output exactly")
  ];
in
{
  inherit checks;
  failures = builtins.filter (c: !c.ok) checks;
  report = builtins.concatStringsSep "; " (map (f: f.msg) (builtins.filter (c: !c.ok) checks));
}
