##
# Package: wineapps
# Purpose: Declarative Wine app manager CLI. Reads the registry generated by
#   modules/system/wine-apps.nix (/etc/wineapps/apps.json) and manages per-app
#   Wine prefixes under $XDG_DATA_HOME/wineprefixes (on odin bind-mounted to
#   /gamez/main/wineprefixes): list/install/uninstall/run/sync.
{
  python3,
  wineWow64Packages,
  winetricks,
  writeShellScriptBin,
}:
writeShellScriptBin "wineapps" ''
  export WINE="${wineWow64Packages.stable}/bin/wine"
  export WINEBOOT="${wineWow64Packages.stable}/bin/wineboot"
  export WINESERVER="${wineWow64Packages.stable}/bin/wineserver"
  export WINETRICKS="${winetricks}/bin/winetricks"
  export WINEPREFIX_BASE="''${WINEPREFIX_BASE:-$HOME/.local/share/wineprefixes}"
  exec ${python3}/bin/python3 ${./wineapps.py} "$@"
''
