#!/usr/bin/env python3
"""wineapps — declarative Wine app manager.

Consumes the registry generated by modules/system/wine-apps.nix
(/etc/wineapps/apps.json by default; override with WINEAPPS_REGISTRY) and
manages per-app Wine prefixes under $XDG_DATA_HOME/wineprefixes (default
~/.local/share/wineprefixes; override with WINEPREFIX_BASE).

Commands:
  wineapps list                  show declared apps + install status
  wineapps install [APP...]      ensure apps are installed (no args: all)
  wineapps uninstall APP...      remove app prefixes
  wineapps run APP [ARGS...]     launch the app's main executable
  wineapps prefix APP            print the app's prefix directory
  wineapps status                wine/winetricks/prefix overview
"""

import argparse
import json
import os
import re
import shlex
import shutil
import subprocess
import sys
import urllib.request
from pathlib import Path

REGISTRY_DEFAULT = "/etc/wineapps/apps.json"


def registry_path() -> Path:
    return Path(os.environ.get("WINEAPPS_REGISTRY", REGISTRY_DEFAULT))


def load_registry() -> dict:
    p = registry_path()
    if not p.exists():
        return {}
    with open(p, encoding="utf-8") as f:
        return json.load(f)


def prefix_root() -> Path:
    env = os.environ.get("WINEPREFIX_BASE")
    if env:
        return Path(env).expanduser()
    data = os.environ.get("XDG_DATA_HOME")
    base = (
        Path(data).expanduser() if data else Path.home() / ".local" / "share"
    )
    return base / "wineprefixes"


def app_prefix(app: dict) -> Path:
    return prefix_root() / app["prefix"]


def resolve_exe(app: dict, prefix: Path):
    exe = app.get("executable")
    return None if not exe else prefix / exe


def is_installed(app: dict, prefix: Path, exe) -> bool:
    if (prefix / ".wineapps-installed").exists():
        return True
    return exe is not None and exe.exists()


def wine_env(prefix: Path, app=None) -> dict:
    env = dict(os.environ)
    env["WINEPREFIX"] = str(prefix)
    if app:
        env["WINEARCH"] = app["arch"]
    wine = os.environ.get("WINE")
    if wine:
        wine_dir = str(Path(wine).parent)
        env["PATH"] = wine_dir + os.pathsep + env.get("PATH", "")
    return env


def run(cmd, env: dict, **kw) -> subprocess.CompletedProcess:
    print("+ " + " ".join(str(c) for c in cmd), file=sys.stderr)
    return subprocess.run(cmd, env=env, **kw)


def wait_wine(env: dict) -> None:
    # Wait until every wine process in this prefix has exited (installer
    # spawned children included). Safe: installers terminate on their own.
    wineserver = os.environ.get("WINESERVER", "wineserver")
    subprocess.run([wineserver, "-w"], env=env, check=False)


def fetch_installer(installer: str, name: str):
    if re.match(r"https?://", installer):
        cache_home = os.environ.get("XDG_CACHE_HOME") or str(
            Path.home() / ".cache"
        )
        cache = Path(cache_home) / "wineapps"
        cache.mkdir(parents=True, exist_ok=True)
        dest = cache / (name + "-" + Path(installer).name)
        if not dest.exists():
            print(f"{name}: downloading {installer}")
            try:
                urllib.request.urlretrieve(installer, dest)
            except (
                Exception
            ) as exc:  # noqa: BLE001 - report any download failure
                print(f"error: download failed: {exc}", file=sys.stderr)
                return None
        return dest
    p = Path(installer).expanduser()
    if not p.exists():
        print(f"error: installer not found: {p}", file=sys.stderr)
        return None
    return p


def install_one(app: dict) -> bool:
    name = app["name"]
    prefix = app_prefix(app)
    exe = resolve_exe(app, prefix)
    if is_installed(app, prefix, exe):
        print(f"{name}: already installed ({prefix})")
        return True

    prefix.mkdir(parents=True, exist_ok=True)
    env = wine_env(prefix, app)

    print(f"{name}: initializing prefix {prefix} ({app['arch']})")
    wineboot = os.environ.get("WINEBOOT", "wineboot")
    if run([wineboot, "-u"], env).returncode != 0:
        print(f"error: wineboot failed for {name}", file=sys.stderr)
        return False
    wait_wine(env)

    for verb in app.get("winetricks") or []:
        print(f"{name}: winetricks {verb}")
        winetricks = os.environ.get("WINETRICKS", "winetricks")
        if run([winetricks, "-q", verb], env).returncode != 0:
            print(
                f"error: winetricks {verb} failed for {name}", file=sys.stderr
            )
            return False
        wait_wine(env)

    installer = app.get("installer")
    if installer:
        local = fetch_installer(installer, name)
        if local is None:
            return False
        extra = shlex.split(app.get("installArgs") or "")
        if str(local).lower().endswith(".msi"):
            cmd = [
                os.environ.get("WINE", "wine"),
                "msiexec",
                "/i",
                str(local),
            ] + extra
        else:
            cmd = [os.environ.get("WINE", "wine"), str(local)] + extra
        print(f"{name}: running installer {local}")
        if run(cmd, env).returncode != 0:
            print(f"error: installer failed for {name}", file=sys.stderr)
            return False
        wait_wine(env)

    (prefix / ".wineapps-installed").write_text(name + "\n", encoding="utf-8")
    print(f"{name}: installed ({prefix})")
    return True


def cmd_list(_args) -> int:
    reg = load_registry()
    if not reg:
        print("no apps declared (features.wine.apps is empty)")
        return 0
    for name in sorted(reg):
        app = reg[name]
        prefix = app_prefix(app)
        exe = resolve_exe(app, prefix)
        if is_installed(app, prefix, exe):
            state = "installed"
        elif app.get("installer"):
            state = "missing"
        else:
            state = "manual"
        comment = app.get("comment") or ""
        print(f"{name}\t{state}\t{app['prefix']}\t{app['arch']}\t{comment}")
    return 0


def cmd_install(args) -> int:
    reg = load_registry()
    if not reg:
        print(
            "error: no apps declared (features.wine.apps is empty)",
            file=sys.stderr,
        )
        return 1
    names = args.apps or sorted(reg)
    code = 0
    for name in names:
        if name not in reg:
            print(f"error: unknown app {name}", file=sys.stderr)
            code = 1
            continue
        if not install_one(reg[name]):
            code = 1
    return code


def cmd_uninstall(args) -> int:
    reg = load_registry()
    code = 0
    for name in args.apps:
        if name not in reg:
            print(f"error: unknown app {name}", file=sys.stderr)
            code = 1
            continue
        app = reg[name]
        prefix = app_prefix(app)
        if not prefix.exists():
            print(f"{name}: no prefix at {prefix}")
            continue
        if app["prefix"] != name:
            print(
                f"error: {name} uses shared prefix '{app['prefix']}'; remove it manually",
                file=sys.stderr,
            )
            code = 1
            continue
        print(f"{name}: removing prefix {prefix}")
        shutil.rmtree(prefix)
    return code


def cmd_run(args) -> int:
    reg = load_registry()
    name = args.app
    if name not in reg:
        print(f"error: unknown app {name}", file=sys.stderr)
        return 1
    app = reg[name]
    if not app.get("executable"):
        print(f"error: {name} has no 'executable' configured", file=sys.stderr)
        return 1
    prefix = app_prefix(app)
    exe = resolve_exe(app, prefix)
    if exe is None or not exe.exists():
        print(f"error: executable not found: {exe}", file=sys.stderr)
        return 1
    env = wine_env(prefix)
    cmd = [os.environ.get("WINE", "wine"), str(exe)] + list(args.rest)
    subprocess.Popen(cmd, env=env, cwd=str(prefix))
    print(f"{name}: launched {exe}")
    return 0


def cmd_prefix(args) -> int:
    reg = load_registry()
    name = args.app
    if name not in reg:
        print(f"error: unknown app {name}", file=sys.stderr)
        return 1
    print(app_prefix(reg[name]))
    return 0


def cmd_status(_args) -> int:
    wine = os.environ.get("WINE") or shutil.which("wine")
    winetricks = os.environ.get("WINETRICKS") or shutil.which("winetricks")
    print(f"wine: {wine or 'not found'}")
    print(f"winetricks: {winetricks or 'not found'}")
    print(f"prefix root: {prefix_root()}")
    reg = load_registry()
    print(f"declared apps: {len(reg)}")
    for name in sorted(reg):
        app = reg[name]
        prefix = app_prefix(app)
        state = (
            "installed"
            if is_installed(app, prefix, resolve_exe(app, prefix))
            else "missing"
        )
        print(f"  {name}\t{state}\t{prefix}")
    return 0


def main() -> int:
    p = argparse.ArgumentParser(prog="wineapps", description=__doc__)
    sub = p.add_subparsers(dest="cmd", required=True)

    sp = sub.add_parser("list", help="show declared apps + install status")
    sp.set_defaults(func=cmd_list)

    sp = sub.add_parser(
        "install", help="ensure apps are installed (no args: all declared)"
    )
    sp.add_argument("apps", nargs="*")
    sp.set_defaults(func=cmd_install)

    sp = sub.add_parser("uninstall", help="remove app prefixes")
    sp.add_argument("apps", nargs="+")
    sp.set_defaults(func=cmd_uninstall)

    sp = sub.add_parser("run", help="launch the app's main executable")
    sp.add_argument("app")
    sp.add_argument("rest", nargs=argparse.REMAINDER)
    sp.set_defaults(func=cmd_run)

    sp = sub.add_parser("prefix", help="print the app's prefix directory")
    sp.add_argument("app")
    sp.set_defaults(func=cmd_prefix)

    sp = sub.add_parser("status", help="overview: wine, winetricks, prefixes")
    sp.set_defaults(func=cmd_status)

    args = p.parse_args()
    return args.func(args)


if __name__ == "__main__":
    sys.exit(main())
