  # general
  remote_control_mode_bg = '#00000000'
  border_fg = '#6c7e96'
  text_fg = '#8d9eb2'
  dimmed_text_fg = '#0a3749'
  # input
  input_text_fg = '#8a2f58'
  result_count_fg = '#8a2f58'
  # results
  result_name_fg = '#0a3749'
  result_line_number_fg = '#005faf'
  result_value_fg = '#00ff00'
  selection_fg = '#005200'
  selection_bg = '#0f2329'
  match_fg = '#8a2f58'
  # preview
  preview_title_fg = '#914e89'
  # modes
  channel_mode_fg = '#ff0000'
  remote_control_mode_fg = '#005200'
  send_to_channel_mode_fg = '#0a3749'
