# Game Scripts Package
#
# Consolidates all gaming-related scripts (gamescope wrappers, CPU affinity tools)
# into a single derivation. Replaces the inline script definitions that were
# previously scattered in modules/user/games/default.nix.
{
  pkgs,
  lib,
  config,
  ...
}:
let
  # Default CPU pin set for affinity wrappers
  # Falls back to 'auto' to detect V-Cache CCD via L3 size at runtime
  pinDefault =
    let
      v = config.profiles.performance.gamingCpuSet or "";
    in
    if v != "" then v else "auto";

  scriptsDir = ./.;
in
{
  # Gamescope preset wrappers
  gamescope-pinned = pkgs.writers.writePython3Bin "gamescope-pinned" { } (
    builtins.readFile (scriptsDir + "/gamescope-pinned.py")
  );

  game-pinned = pkgs.writers.writePython3Bin "game-pinned" { } (
    builtins.readFile (scriptsDir + "/game-pinned.py")
  );

  gamescope-perf = pkgs.writers.writePython3Bin "gamescope-perf" { } (
    builtins.readFile (scriptsDir + "/monitor_utils.py")
    + "\n\n"
    + builtins.readFile (scriptsDir + "/gamescope-perf.py")
  );

  gamescope-quality = pkgs.writers.writePython3Bin "gamescope-quality" { } (
    builtins.readFile (scriptsDir + "/monitor_utils.py")
    + "\n\n"
    + builtins.readFile (scriptsDir + "/gamescope-quality.py")
  );

  gamescope-hdr = pkgs.writers.writePython3Bin "gamescope-hdr" { } (
    builtins.readFile (scriptsDir + "/monitor_utils.py")
    + "\n\n"
    + builtins.readFile (scriptsDir + "/gamescope-hdr.py")
  );

  gamescope-targetfps = pkgs.writers.writePython3Bin "gamescope-targetfps" { } (
    builtins.readFile (scriptsDir + "/monitor_utils.py")
    + "\n\n"
    + builtins.readFile (scriptsDir + "/gamescope-targetfps.py")
  );

  # CPU affinity helpers
  game-affinity-exec = pkgs.writers.writePython3Bin "game-affinity-exec" { } (
    lib.replaceStrings [ "\${pinDefault}" ] [ pinDefault ] (
      builtins.readFile (scriptsDir + "/game_affinity_exec.py")
    )
  );

  game-run = pkgs.writers.writePython3Bin "game-run" { } (
    lib.replaceStrings [ "@pinDefault@" ] [ pinDefault ] (
      builtins.readFile (scriptsDir + "/game_run.py")
    )
  );

  # OptiScaler deployment helper
  optiscaler-install = pkgs.writeShellScriptBin "optiscaler-install" ''
        set -euo pipefail

        GAME_DIR="''${1:-}"
        OPTISCALER="${pkgs.optiscaler}/share/optiscaler"

        if [ -z "$GAME_DIR" ]; then
          echo "Usage: optiscaler-install <game-directory>"
          echo ""
          echo "Example: optiscaler-install ~/.local/share/Steam/steamapps/common/DOOMTheDarkAges"
          echo ""
          echo "Then add to Steam launch options:"
          echo "  WINEDLLOVERRIDES=\"winmm=n,b\" PROTON_FSR4_UPGRADE=1 %command%"
          exit 1
        fi

        if [ ! -d "$GAME_DIR" ]; then
          echo "Error: directory '$GAME_DIR' not found"
          exit 1
        fi

        echo "Installing OptiScaler to: $GAME_DIR"

        # Symlink winmm.dll (preferred method for Doom: The Dark Ages)
        if [ -f "$OPTISCALER/winmm.dll" ]; then
          ln -sf "$OPTISCALER/winmm.dll" "$GAME_DIR/winmm.dll"
          echo "  -> winmm.dll linked"
        fi

        # Symlink OptiScaler folder
        if [ -d "$OPTISCALER/OptiScaler" ]; then
          rm -f "$GAME_DIR/OptiScaler" 2>/dev/null
          ln -sfT "$OPTISCALER/OptiScaler" "$GAME_DIR/OptiScaler"
          echo "  -> OptiScaler/ linked"
        fi

        # Create default config if none exists'
        # Note: we use single quotes within the heredoc trick
        if [ ! -f "$GAME_DIR/OptiScaler.ini" ]; then
          cat > "$GAME_DIR/OptiScaler.ini" << 'INIEOF'
    ; OptiScaler configuration
    ; Generated by optiscaler-install
    ; Game: Doom: The Dark Ages (Vulkan)

    [Upscalers]
    ; Vulkan upscaler: fsr21 (FSR 2.1.2) or fsr22 (FSR 2.2.1)
    VulkanUpscaler=auto

    [UpscalerControl]
    ; Enable/disable specific upscalers
    EnableFsr22=true
    EnableFsr31=true
    EnableXess=true

    [Quality]
    ; Upscaling quality: UltraQuality, Quality, Balanced, Performance, UltraPerformance
    Quality=Quality

    [Output]
    ; Output scaling: 1.0 = native, 0.75 = 75% render scale, etc.
    RenderScale=1.0

    [FrameGen]
    ; Enable FSR 3 Frame Generation (DX12/VK interop)
    EnableFrameGen=true
    INIEOF
          echo "  -> OptiScaler.ini created (defaults)"
        else
          echo "  -> OptiScaler.ini already exists, keeping"
        fi

        echo ""
        echo "Done! Add this to Steam launch options for the game:"
        echo "  WINEDLLOVERRIDES=\"winmm=n,b\" PROTON_FSR4_UPGRADE=1 %command%"
  '';
}
