{
  lib,
  neg,
  config,
  ...
}:
let
  lockDir = config.lib.neg.path "files/gui/hypr/hyprlock";
  lockNames = builtins.attrNames (builtins.readDir lockDir);
  # Fragment shaders for HyprWindowShade: linked as a directory so the paths in
  # hyprwindowshade.lua (~/.config/hypr/shaders/<name>.glsl) resolve.
  shadeDir = config.lib.neg.path "files/gui/hypr/shaders";
  shadeNames = builtins.attrNames (builtins.readDir shadeDir);
  ruHotkeys = config.features.input.ruHotkeys or { };
  ruHotkeysEnabled = ruHotkeys.enable or false;
  usClasses = ruHotkeys.usClasses or [ ];
  usIdx = toString (ruHotkeys.usLayoutIndex or 0);
in
{
  generateFileLinks =
    {
      hyprlandConfText,
      hyprlandLuaText,
    }:
    neg.mkHomeFiles (
      {
        ".config/hypr/hyprland.conf".text = hyprlandConfText;

        ".config/hypr/hyprland.lua".text = hyprlandLuaText;

        ".config/hypr/hyprlock.conf".text = config.lib.neg.readFile "files/gui/hypr/hyprlock.conf";

        # hyprglass defaults, also deployed as a file: `hyprglass-apply` re-reads
        # them to push the settings into a *running* session (the plugin only
        # reads them when they are pushed) and the Glass panel keeps its overrides
        # next to this file in hyprglass.json.
        ".config/hypr/hyprglass.lua".text = config.lib.neg.readFile "files/gui/hypr/hyprglass.lua";

        # HyprWindowShade rules (per-window / per-layer fragment shaders). Pushed
        # into the running session by hyprwindowshade-setup, same load-then-push
        # pattern as hyprglass.lua.
        ".config/hypr/hyprwindowshade.lua".text =
          config.lib.neg.readFile "files/gui/hypr/hyprwindowshade.lua";

        ".config/hypr/hypridle.conf".text = ''
          # Hypridle — idle configuration
          # Idle locking temporarily disabled (2026-08-31): hyprlock removed.
          # No DPMS off: the monitor stays powered (avoids the DPMS wake-up bug).
          # Restore the auto-lock by re-adding the lock_cmd + 120 s listener from
          # git history together with the hyprlock package.
        '';

        # Hyprscratch config: Telegram scratchpad (name without dots — togglespecialworkspace breaks on '.')
        ".config/hypr/hyprscratch.conf".text = ''
          telegram {
              class = org.telegram.desktop
              command = Telegram
              options = special
              # Fresh spawns land right-aligned; user geometry (saved by
              # scratchpad-geometry.service) wins once the window is moved.
              rules = size monitor_w*0.3 monitor_h-60; move monitor_w*0.7-8 8
          }
          music {
              class = music
              offset = 0 30%
          }
        '';

        # Ensure local.d directory exists with at least one .lua file so the glob never fails
        ".config/hypr/local.d/00-override.lua".text =
          "-- Local Hyprland overrides (Lua API)
-- Use hl.env(), hl.config(), hl.bind(), hl.window_rule() etc.
-- See ~/.config/hypr/hyprland.lua for reference
";
      }
      // (neg.mkDirLinks ".config/hypr/hyprlock" lockDir lockNames)
      // (neg.mkDirLinks ".config/hypr/shaders" shadeDir shadeNames)
      // lib.optionalAttrs ruHotkeysEnabled {
        # Config of the layout daemon (features.input.ruHotkeys, see
        # hyprland/ru-layout.nix). `keyboards` stays unset on purpose: the daemon
        # learns every keyboard that emits an `activelayout` event, so no device
        # names are pinned here (kanata's virtual device included).
        # `default_layouts` maps an XKB group index to the Hyprland window classes
        # pinned onto it on focus; the class list comes from usClasses. A window
        # matching nothing starts on group 0 (= `us` for kb_layout = "us,ru") and
        # keeps whatever it was switched to.
        ".config/hyprland-per-window-layout/options.toml".text = ''
          # Generated by modules/user/nix-maid/hyprland/files.nix — do not edit.

          [[default_layouts]]
          ${usIdx} = [${lib.concatMapStringsSep ", " (c: ''"${c}"'') usClasses}]
        '';
      }
    );
}
